### ISSUE TITLE
[FR]: Support passing `args` to `js_test`

### ISSUE THREAD

**Issue by sashamor** [aspect-build/rules_js#1014]
### What is the current behavior?

A nice pattern for running tests using Node dependencies as binaries looks like:

```starlark

directory_path(
    name = "vitest_entry_point",
    directory = "//:node_modules/vitest/dir",
    path = "vitest.mjs",
)

js_test(
    name = "tests",
    chdir = package_name(),
    data = [
        "path/to/tests.js"
    ],
    entry_point = ":vitest_entry_point",
)

```

However, there is no way to pass arguments to this, test e.g. `vitest --run`.

A current workaround involves writing a wrapper JS file, e.g.:

```js
process.argv.push('--run')
import('vitest/vitest.mjs')
```

and then setting that file as the `entry_point`. But, this causes issues with `chdir` and paths.

### Describe the feature

Ideally, `js_test` would support `args` so we could write this with:

```starlark

directory_path(
    name = "vitest_entry_point",
    directory = "//:node_modules/vitest/dir",
    path = "vitest.mjs",
)

js_test(
    name = "tests",
    args = ["--run"],
    chdir = package_name(),
    data = [
        "path/to/tests.js"
    ],
    entry_point = ":vitest_entry_point",
)

```

**Comment by gregmagolan** [comment]
`args` is already supported as it is a built-in attribute to all `*_test` rules in Bazel: https://bazel.build/reference/be/common-definitions#common-attributes-tests

**Comment by sashamor** [comment]
You're right, my bad - my example code actually works. Thank you.
