### ISSUE TITLE
Code highlight for npm/js_package dependencies

### ISSUE THREAD

**Issue by bazaglia** [aspect-build/rules_js#105]
While migrating from `rules_nodejs` I came across a limitation that affects the developer experience a lot. The previous `yarn install` rule I used can create and track the node_modules folder as a managed directory on Bazel.

I understand `rules_js` has another approach, but having the node_modules folder allowed all my external npm dependencies and local libraries (`js_library`) to be available to IDEs/text editors like VSCode. Right now, all the dependencies are seen as missing since there's no way for them to be found, removing access to definitions, syntax highlight, linters, etc. while coding.

Are there any alternatives or recommended approaches?

**Comment by alexeagle** [comment]
As you probably saw, there's a proposal likely to land to remove `managed_directories`.

The recommended way to teach TS language service about mapping package names to locations in the monorepo is with the `paths` property, aka. path mapping.

You can still run `pnpm install` to get a local `node_modules` folder for the IDE. How else is rules_js different from rules_nodejs without managed_directories?

**Comment by bazaglia** [comment]
The only difference I can think of now is that the rules_nodejs's js_library links local packages to the node_modules. Wondering how to achieve the same behavior with rules_js?

Example based on my use case: I have a lot of protobuf definitions and a target that outputs interfaces for them. They're local js libraries that need to be available at the IDE.

**Comment by alexeagle** [comment]
rules_js also links local packages into the node_modules. However the `bazel-bin/path/to/package/node_modules` tree is created lazily as actions run that require populating it with symlinks to the pnpm store.

Protobufs are a problem across all languages. See recent chatter about this in #go on bazel slack like https://bazelbuild.slack.com/archives/CDBP88Z0D/p1652721846297049.
The practical answer, though not "bazel-idiomatic", is to output the generated protos to the source tree for non-Bazel tooling to be able to locate them. Anything else is an uphill battle against the expectations of those tools.

**Comment by bazaglia** [comment]
Maybe I've missed something or the docs don't state it yet, but I just realized not only the js_package targets aren't linked to node_modules, but my application doesn't find the package at all.

If I have my `js_package` like:

```bzl
js_package(
    name = "my_package",
    srcs = [":compile_ts"], # aspect swc rule that transpiles .ts to .js
    package = "my-package-name",
    replace_prefixes = {
        "src/": "",
    },
)
```

When I include the target to "my_package" in the `data` array on the `swc` or `js_binary` targets, it just doesn't work. I can't see anything linked in the node_modules inside the bazel-bin and  my application throws `Error: Cannot find module 'my-package-name'`.

**Comment by bazaglia** [comment]
Got it! I needed to use the `link_js_package` rule:


```bzl
load("@npm//:defs.bzl", "link_js_packages", "package")
load("@aspect_rules_js//js:defs.bzl", "link_js_package")

link_js_packages()

link_js_package(
    name = package("@ingka/grpc-error").name,
    src = "//backend/packages/my-package:my_package",
    deps = [package("protobufjs")],
)
```

Then instead of providing my package target in the data, I pass `package("my-package-name)`:

```bzl
swc(
    name = "compile_ts",
    srcs = glob(["src/**/*.ts"]),
    data = [
        package("my-package-name"),
        "@npm//joi",
    ],
    source_maps = True,
    swcrc = ".swcrc",
)
```

I only noticed afterward that there was an example in this repo. My bad. Thank you for the nice discussion above. Like you said I'll use the `paths` for mapping dependencies in the IDE. The node_modules in the bazel-bin indeed has it all linked.

**Comment by bazaglia** [comment]
Got it! I needed to use the `link_js_package` rule:


```bzl
load("@npm//:defs.bzl", "link_js_packages", "package")
load("@aspect_rules_js//js:defs.bzl", "link_js_package")

link_js_packages()

link_js_package(
    name = package("my-package-name").name,
    src = "//backend/packages/my-package:my_package",
    deps = [package("protobufjs")],
)
```

Then instead of providing my package target in the data, I pass `package("my-package-name)`:

```bzl
swc(
    name = "compile_ts",
    srcs = glob(["src/**/*.ts"]),
    data = [
        package("my-package-name"),
        "@npm//joi",
    ],
    source_maps = True,
    swcrc = ".swcrc",
)
```

I only noticed afterward that there was an example in this repo. My bad. Thank you for the nice discussion above. Like you said I'll use the `paths` for mapping dependencies in the IDE. The node_modules in the bazel-bin indeed has it all linked.

**Comment by alexeagle** [comment]
Ha, I was struggling with this too and your answer helped me in rules_ts. It's very new and needs more docs and better error messages.
Let me know if there's still something to fix (including where the error handling) could be more helpful)
