### ISSUE TITLE
[Bug]: incorrect `BAZEL_BINDIR` generated in the image layer

### ISSUE THREAD

**Issue by christian-roggia** [aspect-build/rules_js#1064]
### What happened?

Let us take as an example a pseudo project with a TypeScript (Node.js + TS) binary that looks like this:
```
js_binary(
    name = "myapp",
    data = [
        "//:node_modules",
        "//myapp/src",
    ],
    entry_point = "//myapp/src:index.js",
    env = {
        "TS_NODE_PROJECT": "myapp/configuration/runtime/typescript/tsconfig.json",
        "NODE_OPTIONS": "--require tsconfig-paths/register --require ts-node/register",
    },
)
```

This configuration works correctly when running `bazel run //myapp`:

- Please notice the relative path `myapp/configuration/runtime/typescript/tsconfig.json` used at runtime to overwrite the `tsconfig.json` path for Node.js.
- Please notice that this path is correctly defined relative to the root of the Bazel project.

The same can be verified to be correct and working via `js_run_devserver`:
```
js_run_devserver(
    name = "devserver",
    args = [
        "--require tsconfig-paths/register",
        "--require ts-node/register",
        "myapp/src/index.js",
    ],
    command = "node",
    data = [
        "//:node_modules",
        "//myapp/src",
    ],
    env = {
        "TS_NODE_PROJECT": "myapp/configuration/runtime/typescript/tsconfig.json",
    },
)
```

This configuration also works correctly when running `bazel run //myapp:devserver`.

Now, when using `js_image_layer` according to the documentation and e2e / examples, something goes wrong:

```
js_image_layer(
    name = "layers",
    binary = ":myapp",
    root = "/workspace",
    visibility = ["//visibility:__pkg__"],
)

filegroup(
    name = "app_tar",
    srcs = [":layers"],
    output_group = "app",
)

container_layer(
    name = "app_layer",
    tars = [":app_tar"],
)

filegroup(
    name = "node_modules_tar",
    srcs = [":layers"],
    output_group = "node_modules",
)

container_layer(
    name = "node_modules_layer",
    tars = [":node_modules_tar"],
)

container_image(
    name = "image",
    architecture = "amd64",
    base = "@debian_amd64//image",
    cmd = ["/workspace/myapp/myapp"],
    entrypoint = ["bash"],
    layers = [
        ":app_layer",
        ":node_modules_layer",
    ],
    visibility = ["//visibility:public"],
)
```

This will fail and Node.js will complain that it cannot find configuration files such as `tsconfig.json`.

This is due to the variable `BAZEL_BINDIR` being hardcoded to `.` which is, in my opinion, incorrect and inconsistent with the behavior of `js_binary` and `js_run_devserver`.

- **expected**: `BAZEL_BINDIR` to be equal to `/workspace/myapp/myapp.runfiles/com_myapp_codebase`
- - where `com_myapp_codebase` is the name of the Bazel workspace
- **actual**: `BAZEL_BINDIR` is equal to `/workspace/myapp` (i.e. `.`)
- - which is incorrect as the lookup of files like `myapp/configuration/runtime/typescript/tsconfig.json` will fail

This is due to the following hardcoded bash script:

https://github.com/aspect-build/rules_js/blob/7b1e6e521fa702f4561eeb39e99571e4b86df3e2/js/private/js_image_layer.bzl#L173

The following workaround works for us:
```
# The following container image contains 2 major workarounds:
#
# - the value `cmd` should be set to `/[root]/[package]/[js_binary]`
#   according to the documentation of `aspect_rules_js`, but that bash script
#   contains an invalid `BAZEL_BINDIR` export which results in Node.js failing
#   to start properly with TypeScript enabled.
#
# - the value `env` shouldn't include `BAZEL_BINDIR` as it should be already
#   defined by the entrypoint script described in the previous point.

container_image(
    name = "image",
    architecture = "amd64",
    base = "@debian_amd64//image",
    cmd = ["/workspace/myapp/myapp.runfiles/com_myapp_codebase/myapp/myapp.sh"],
    entrypoint = ["bash"],
    env = {
        "BAZEL_BINDIR": "/workspace/myapp/myapprunfiles/com_myapp_codebase",
    },
    layers = [
        ":app_layer",
        ":node_modules_layer",
    ],
    visibility = ["//visibility:public"],
)
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: aspect 5.3.4

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: rules_ts-1.4.0 / rules_js-1.26.0

Language(s) and/or frameworks involved: Node.js (tested with 18.x and 17.x)

**Comment by thesayyn** [comment]
the problem here is that you don't set the workdir in your container_image rule.

Also, see a thread on why we don't set it automatically, by making assumptions.  https://github.com/aspect-build/rules_js/issues/921#issuecomment-1505480215

**Comment by christian-roggia** [comment]
As per suggestion, this fixes the issue, thank you.

```
container_image(
    name = "image",
    architecture = "amd64",
    base = "@debian_amd64//image",
    cmd = ["/workspace/myapp/myapp"],
    entrypoint = ["bash"],
    layers = [
        ":app_layer",
        ":node_modules_layer",
    ],
    visibility = ["//visibility:public"],
    workdir = "/workspace/myapp/myapp.runfiles/com_myapp_codebase",
)
```
