### ISSUE TITLE
[Bug]: Link to Bazel Slack is not working

### ISSUE THREAD

**Issue by agirorn** [aspect-build/rules_js#1070]
### What happened?

The link in the readme to the Bazel Slack channel no longer works. When I got there then, it presented me with this message "This link is no longer active"

![Screenshot 2023-05-16 at 16 07 20](https://github.com/aspect-build/rules_js/assets/261378/30a50637-16ab-4309-bed4-987218a05ffe)

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

**Comment by gregmagolan** [comment]
Hmm. The link we have here is the same URL that is in the footer of the https://bazel.build/community page. Closing this here as it is a bazel issue. Could you please re-open the issue in the bazel repository? https://github.com/bazelbuild/bazel

cc @alexeagle
