### ISSUE TITLE
Shorthand for all packages in an npm namespace (e.g. `@npm//@types`)

### ISSUE THREAD

**Issue by jfirebaugh** [aspect-build/rules_js#109]
With rules_nodejs, I was sometimes using `deps = ["@npm//@types", ...]` in `ts_project` as a convenient way to depend on all `@types` packages in the repository. Are there any plans to support that in rules_js as well?

**Comment by gregmagolan** [comment]
Ahh yes. Those are very useful. Thanks for the reminder. I added the support in #125. If you use pnpm workspaces for first party deps then first party deps are including in the scope targets.
