### ISSUE TITLE
[Bug]: rules_js can’t handle two pnpm projects in the same bazel module/repo

### ISSUE THREAD

**Issue by kreempuff** [aspect-build/rules_js#1123]
### What happened?

It seems as if the [rules_js](https://github.com/aspect-build/rules_js) project can’t handle having two separate pnpm projects in the same repo with bazel modules. Both projects use [`npm_translate_lock`](https://github.com/aspect-build/rules_js/blob/b831fe34610054bd7a180e339e5befff1332bc54/npm/private/npm_translate_lock.bzl#L136) and try to create a “pnpm” repo. The repo name and creation is hard coded. Every call to `npm_translate_lock` [tries to create a new pnpm](https://github.com/aspect-build/rules_js/blob/b831fe34610054bd7a180e339e5befff1332bc54/npm/private/npm_translate_lock.bzl#L474) repo. They use the the same extension (extensions are identified by their path and file) so they have the same [visibility](https://bazel.build/external/extension#repository_names_and_visibility).

Interestingly enough, the [`pnpm_repository`](https://github.com/aspect-build/rules_js/blob/b831fe34610054bd7a180e339e5befff1332bc54/npm/private/pnpm_repository.bzl#L9) function [checks for an already existing rule](https://github.com/aspect-build/rules_js/blob/b831fe34610054bd7a180e339e5befff1332bc54/npm/private/pnpm_repository.bzl#L20) with the same name. I don’t know why it’s not working.

### Error

```bash
ERROR: Traceback (most recent call last):
	File "/<redacted>/2724d502befac904637f0c6347844119/external/aspect_rules_js~override/npm/extensions.bzl", line 21, column 31, in _extension_impl
		npm_translate_lock(
	File "/<redacted>/2724d502befac904637f0c6347844119/external/aspect_rules_js~override/npm/private/npm_translate_lock.bzl", line 474, column 25, in npm_translate_lock
		_pnpm_repository(name = "pnpm", pnpm_version = pnpm_version)
	File "/<redacted>/2724d502befac904637f0c6347844119/external/aspect_rules_js~override/npm/private/pnpm_repository.bzl", line 21, column 20, in pnpm_repository
		_npm_import(
	File "/<redacted>/2724d502befac904637f0c6347844119/external/aspect_rules_js~override/npm/private/npm_import.bzl", line 1139, column 20, in npm_import
		npm_import_rule(
Error in repository_rule: A repo named pnpm is already generated by this module extension at /<redacted>/2724d502befac904637f0c6347844119/external/aspect_rules_js~override/npm/private/npm_import.bzl:1139:20
ERROR: error evaluating module extension npm in @aspect_rules_js~override//npm:extensions.bzl
```

### Version

Development (host) and target OS/architectures: 

M1 Mac for both

Output of `bazel --version`:

Bazelisk version: development
Starting local Bazel server and connecting to it...
Build label: 6.1.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Mar 6 17:10:27 2023 (1678122627)
Build timestamp: 1678122627
Build timestamp as int: 1678122627

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

`bazel_dep(name = "aspect_rules_js", version = "1.28.0")`

Language(s) and/or frameworks involved:

### How to reproduce

_Reproduced in repo_: https://github.com/kreempuff/rules-js-pnpm-issue

**Comment by gregmagolan** [comment]
Thanks for the bug report. The underlying issue comes from this line of code:

https://github.com/aspect-build/rules_js/blob/main/npm/private/npm_translate_lock.bzl#L477

To work-around the issue, you should be able to set `pnpm_version = None` on one of the two `npm_translate_lock` calls. However, looks like there is another bug with `bzlmod` where this attribute must be a string and cannot be set to None.

Fix should be trivial so I'll put up a quick PR.

**Comment by gregmagolan** [comment]
Actually, this bug looks specific to bzlmod since when using WORKSPACE the `pnpm` repository is behind a maybe: https://github.com/aspect-build/rules_js/blob/main/npm/private/pnpm_repository.bzl#L20

**Comment by kreempuff** [comment]
> Actually, this bug looks specific to bzlmod since when using WORKSPACE the pnpm repository is behind a maybe:

Right, it looks like the `maybe` isn't working the way we expect with Bazel modules. I'm not sure if there's a new method to use or what

**Comment by kreempuff** [comment]
I also tried using a [`maybe`](https://bazel.build/rules/lib/repo/utils#maybe) on my local debugging session but that didn't work either

**Comment by gregmagolan** [comment]
There are differences in how external repositories are named between bzlmod and WORKSPACE that likely makes the `existing_rule` check common as a WORKSPACE patterns not work as expected in bzlmod. In any case, #1149 will fix the issue. I tested against your repro.

**Comment by loeffel-io** [comment]
hey @gregmagolan,

i have a similar issue: 

```bash
ERROR: /private/var/tmp/_bazel_loeffel/e57a65c62a593856a1cb4cf5c0f7f207/external/aspect_rules_js+/npm/extensions.bzl:46:28: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_loeffel/e57a65c62a593856a1cb4cf5c0f7f207/external/aspect_rules_js+/npm/extensions.bzl", line 29, column 39, in _npm_extension_impl
                _npm_translate_lock_bzlmod(attr)
        File "/private/var/tmp/_bazel_loeffel/e57a65c62a593856a1cb4cf5c0f7f207/external/aspect_rules_js+/npm/extensions.bzl", line 46, column 28, in _npm_translate_lock_bzlmod
                npm_translate_lock_rule(
Error in repository_rule: A repo named npm is already generated by this module extension at /private/var/tmp/_bazel_loeffel/e57a65c62a593856a1cb4cf5c0f7f207/external/aspect_rules_js+/npm/extensions.bzl:46:28
ERROR: error evaluating module extension @@aspect_rules_js+//npm:extensions.bzl%npm
INFO: Elapsed time: 0.530s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
FAILED:
    Fetching module extension @@aspect_rules_js+//npm:extensions.bzl%npm; starting
```

how to solve this situation? unique `npm_translate_lock` names?

thanks

**Comment by loeffel-io** [comment]
looks like this is doing the job - is this as intended?

```starlark
npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
npm.npm_translate_lock(
    name = "npm_global_proto", # instead of npm
    npmrc = "//:.npmrc",
    pnpm_lock = "//:pnpm-lock.yaml",
    public_hoist_packages = {},
    use_home_npmrc = True,
    verify_node_modules_ignored = "//:.bazelignore",
)
use_repo(npm, npm = "npm_global_proto")
```
