### ISSUE TITLE
js rules should be hermetic and not follow symlinks out of the sandbox

### ISSUE THREAD

**Issue by jfirebaugh** [aspect-build/rules_js#114]
I noticed some of my uses of `js_binary` were accidentally escaping the sandbox through `__dirname`. For consistency with `nodejs_binary` and per previous discussions in rules_nodejs (e.g. https://github.com/bazelbuild/rules_nodejs/issues/109), `--preserve-symlinks` should be the default.

**Comment by alexeagle** [comment]
Good catch, that seems obviously wrong, sending PR with repro

**Comment by jfirebaugh** [comment]
It looks like there may be side effects with pnpm-style package linking. I'm still debugging this, but locally setting `node_options = ["--preserve-symlinks", "--preserve-symlinks-main"]` causes requires of transitive dependencies to start failing.

**Comment by alexeagle** [comment]
yeah I found the same thing, I think pnpm does rely on some amount of walking symlinks into the CAS.
Will leave for Greg to ponder.

**Comment by jfirebaugh** [comment]
My 2¢, if it turns out pnpm isolated linking is fundamentally incompatible with `--preserve-symlinks`: I would prefer hermeticity with hoisted modules over non-hermeticity and isolated modules.

**Comment by alexeagle** [comment]
We have the sandbox guards in rules_nodejs/package/patches which is probably needed to improve hermeticity. Some packages follow symlinks regardless of what require does.

**Comment by gregmagolan** [comment]
AFAIK `--preserve-symlinks` comes with issues when used with pnpm style symlinked node_modules structure. I haven't investigated it so it might work in some cases however I'd rather not flip it to default. My plan to bring in the symlink guards node patches from rules_nodejs and use them when running in the sandbox.

**Comment by gregmagolan** [comment]
It's near to top of my list to bring in here next. Should be a fairly quick fix which I could get done over the long weekend here.

**Comment by gregmagolan** [comment]
Started on it today, https://github.com/aspect-build/rules_js/pull/133.

But I'll need to tweak the node patches so they just guard the sandbox but still allow symlinks to be resolved within the sandbox. I'll save it for another day when I have a fresh brain.

**Comment by alex-torok** [comment]
I just got bit by this - it appears that even the entrypoint script for `js_test` targets is being resolved out of the sandbox. I've put up an example and a writeup at https://github.com/alex-torok/rules_js/pull/1.

I have some targets that select their dependencies based on the result of a configuration transition, and the sandbox escape is causing them to not resolve the dependencies. The proper dependencies are placed in the runfiles, but aren't in the configured output directory where the test escapes to.

**Comment by gregmagolan** [comment]
https://github.com/aspect-build/rules_js/pull/133 impl is done on this and looks to be working as expected; I'm going to port over unit tests from https://github.com/bazelbuild/rules_nodejs/tree/stable/packages/node-patches/test/fs to wrap it up  for landing

**Comment by alex-torok** [comment]
Confirming that after #133, my tests are able to correctly resolve dependencies because they don't escape the sandbox.
