### ISSUE TITLE
[FR]: Help users discover exclude_declarations_from_npm_packages

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#1206]
### What is the current behavior?

Users may have slow type-checks in their devloop due to npm_package that contain .d.ts files. #1205 adds a flag to avoid this, but it's hard to discover

### Describe the feature

maybe js_run_devserver and js_test could sense the value of the flag and alert the user "it looks like you're including typecheck actions in your  devloop", but we can't tell if they used the `transpiler` attribute of ts_project, so we might over-warn.

**Comment by jbedard** [comment]
This has been deprecated and will most likely be removed in rules_js 3+ and using `js_library` for packages is recommended instead.
