### ISSUE TITLE
[FR]: Add visibility mapping to npm_link_all_packages

### ISSUE THREAD

**Issue by DavidANeil** [aspect-build/rules_js#1208]
### What is the current behavior?

`npm_link_all_packages` does not let you specify visibility on the targets it creates.
`npm_link_package` does let you specify visibility.

### Describe the feature

`npm_link_all_packages` should take an attribute that lets the end-user define visibility constraints on the linked packages.
It is possible this would need to be defined on `npm_translate_lock` or `npm_import` instead.  I'm pretty new to this ruleset, so I'm not sure I've got the layering correctly just yet.

Motivation:
I want to be able to add things to our `package.json` (for example, a package to help with build tools), without allowing all targets (for example, our application code) to depend on it.  I think visibility would work well for that.

I am imagining an API like this:
```starlark
npm_link_all_packages(
    name = "node_modules",
    visibility_map = {
        "@types/node": ["//src/ecma/nodejs:__subpackages__"],
        "protobufjs": ["//build:__subpackages__"],
    },
)
```

All unlisted visibilities would default to `["//visibility:public"]`.
Listing a name that isn't being generated should probably fail the analysis.

**Comment by alexeagle** [comment]
I think the way it's intended to work is, a given package lists the direct dependencies in its package.json file, and the visibility we stamp on targets beneath `node_modules` is based on that. Transitives are not visible, direct are.
That is, so far we've taken the granularity of `package.json` to indicate the granularity of visibility, and avoided adding another way.

It may still be reasonable to add what you're suggesting as an override, but when you say "our `package.json`" that makes me think you have only one of them, which isn't the typical intended usage here; we expect pnpm workspaces are being used.

**Comment by DavidANeil** [comment]
I believe this is solved by https://github.com/aspect-build/rules_js/commit/f60b9b5ca31472cc29fd3acf48a27c9284f0d85d
