### ISSUE TITLE
[Bug]: Slack invite link in README is broken

### ISSUE THREAD

**Issue by Qinusty** [aspect-build/rules_js#1224]
### What happened?

Slack link in README [here](https://github.com/aspect-build/rules_js/blame/7e17e8767c5d83929fddb5d9edfa5f5d4318624b/README.md#L24) is no longer working.

Also the link in the issue template for bazel slack doesn't work either.

### Version

N/A

**Comment by mattem** [comment]
Thanks for the issue! Aspect don't own the link or the community Slack, however I've pinged the Google folks that can manage it they say it should be working again now. As far as I can see, there is nothing else actionable here, so going to close this.
