### ISSUE TITLE
[Bug]: Bazel managed pnpm can't resolve pnpm-lock.yml file merge conflicts

### ISSUE THREAD

**Issue by KatSick** [aspect-build/rules_js#1279]
### What happened?

During merge conflicts, in `package.json` files you may end up with `pnpm-lock.yml` file state where there is merge conflicts in `pnpm-lock.yml`.

`pnpm` already have mechanism to resolve this conflicts https://pnpm.io/git#merge-conflicts, however, it can't be used if you run `pnpm` from the `bazel` (which as I understand is the recommended way of working with pnpm under rules_js) like:

```bash
bazel run -- @pnpm//:pnpm --dir $PWD "$@" install
```
command above will just crash, since Bazel can't read the pnpm lock file in the first place

### Version

bazel version
Bazelisk version: development
Build label: 6.2.1
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 2 17:00:10 2023 (1685725210)
Build timestamp: 1685725210
Build timestamp as int: 1685725210

rules_js: 1.31.0

### How to reproduce

Use pnpm-lock file from https://github.com/pnpm/pnpm/blob/37fffbefa5a9136f2e189c01a5edf3c00ac48018/packages/supi/test/lockfile.ts#L1237

Run `bazel run  -- @pnpm//:pnpm --dir $PWD "$@" install` (see crash)
Run local pnpm `pnpm install` (see successfully resolved conflict)

**Comment by jbedard** [comment]
Fixed in https://github.com/aspect-build/rules_js/pull/1287.

We could potentially *partially* parse the yaml instead of the parser returning nothing which would align with pnpm more, but the crash is fixed.
