### ISSUE TITLE
[Bug]: pnpm 8.6.7 doesn't work when invoked through @pnpm//:pnpm js_binary

### ISSUE THREAD

**Issue by matthewjh** [aspect-build/rules_js#1301]
### What happened?

On rules_js v1.32.5, support for pnpm 8.6.7 was [added](https://github.com/aspect-build/rules_js/pull/1290), but it doesn't work. There appear to be a couple of different failure modes:

```shell
bazel run @pnpm//:pnpm install -- --dir=$PWD
INFO: Build completed successfully, 2 total actions
Scope: all 2 workspace projects
 MODULE_NOT_FOUND  Cannot find module '/Users/mhill/bazel/3c3e59429c86c7585f0ffa57350a75ac/execroot/web/bazel-out/darwin_arm64-fastbuild/bin/external/pnpm/pnpm.sh.runfiles/pnpm/package/dist/worker.js'

Error: Cannot find module '/Users/mhill/bazel/3c3e59429c86c7585f0ffa57350a75ac/execroot/web/bazel-out/darwin_arm64-fastbuild/bin/external/pnpm/pnpm.sh.runfiles/pnpm/package/dist/worker.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:164:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:741:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
```

```shell
bazel run @pnpm//:pnpm install -- --dir=$PWD
INFO: Build completed successfully, 1 total action
Scope: all 2 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +3085
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ERROR  Worker pnpm#7 exited with code 1

pnpm: Worker pnpm#7 exited with code 1
    at Worker.<anonymous> (/Users/mhill/bazel/3c3e59429c86c7585f0ffa57350a75ac/execroot/web/bazel-out/darwin_arm64-fastbuild/bin/external/pnpm/pnpm.sh.runfiles/pnpm/package/dist/pnpm.cjs:81745:27)
    at Worker.emit (node:events:514:28)
    at [kOnExit] (node:internal/worker:289:10)
    at Worker.<computed>.onexit (node:internal/worker:209:20)
Progress: resolved 3085, reused 0, downloaded 0, added 0
```

It looks like at least one of these is caused by the fact that the pnpm js_binary runfiles only includes `package/dist/pnpm.cjs` rather than the whole package:

https://github.com/aspect-build/rules_js/blob/main/npm/private/pnpm_repository.bzl#L40

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

6.3.1

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

http_archive(
        name = "aspect_rules_js",
        sha256 = "8563dd34e75ce989fd2e45ad6dd527c6e6fafacb2dcf6f7dd36ca6e7fb0ca670",
        strip_prefix = "rules_js-1.32.5",
        url = "https://github.com/aspect-build/rules_js/releases/download/v1.32.5/rules_js-v1.32.5.tar.gz",
    )

Language(s) and/or frameworks involved:

### How to reproduce

```shell
Delete node_modules
Invoke pnpm through bazel
```

**Comment by gzm0** [comment]
Interestingly, I cannot reproduce this in the rules_js repository itself:

```sh
rules_js/examples/js_binary$ bazel run @pnpm -- install --dir $PWD -D -E react-router --lockfile-only
```

works just fine.

I have also tried removing `.bazeliskrc` to use vanilla bazel 6.3.1 (as opposed to aspect 5.7.2). Still works. I'll start isolating from a clean room rules_js setup.

**Comment by gzm0** [comment]
I cannot reproduce this with a clean room setup:

- WORKSPACE from https://github.com/aspect-build/rules_js/releases/tag/v1.32.6
- touch BUILD.bazel
- echo "node_modules" > .bazelignore
- echo "{}" > package.json
- touch pnpm-lock.yaml
- echo "6.3.2" > .bazelverison
- `bazel run @pnpm -- install --dir $PWD --fix-lockfile`
- `bazel run @pnpm -- install --dir $PWD -D -E react-router  --lockfile-only`

Works just fine.

**Comment by gzm0** [comment]
It seems to depend on the amount of things to be installed. The following fails in rules_js 1.32.6 (but succeeds in 1.32.3):

```sh
$ bazel run @pnpm -- install --dir $PWD -D -E jest typescript eslint jest-extended
INFO: Analyzed target @pnpm//:pnpm (26 packages loaded, 96 targets configured).
INFO: Found 1 target...
Target @pnpm//:pnpm up-to-date:
  bazel-bin/external/pnpm/pnpm.sh
INFO: Elapsed time: 0.143s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/external/pnpm/pnpm.sh install --dir /home/tos/dh/tmp-rules-js -D -E jest typescript eslint jest-extended
Packages: +340
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ERROR  Worker pnpm#3 exited with code 1

pnpm: Worker pnpm#3 exited with code 1
    at Worker.<anonymous> (/home/tos/.cache/bazel/_bazel_tos/10870a2ca1a34443d8182830015af23b/execroot/__main__/bazel-out/k8-fastbuild/bin/external/pnpm/pnpm.sh.runfiles/pnpm/package/dist/pnpm.cjs:81745:27)
    at Worker.emit (node:events:513:28)
    at Worker.[kOnExit] (node:internal/worker:287:10)
    at Worker.<computed>.onexit (node:internal/worker:202:20)
Progress: resolved 341, reused 0, downloaded 0, added 0
```

**Comment by gzm0** [comment]
I managed to reproduce this without "many packages": Take the steps above and remove `--lockfile-only` in the last `install` step (`-E -D` can also be removed, they don't matter).

I suspect `--lockfile-only` does not trigger the worker mechanism (since it doesn't need to download files or create a lot of symlinks).

**Comment by gzm0** [comment]
I also found out why I couldn't reproduce this in rules_js: It uses a different pnpm version:

https://github.com/aspect-build/rules_js/blob/b65fc28ad12699b8d52dd9a42e2e2be54891b0b4/WORKSPACE#L155-L157
