### ISSUE TITLE
[Bug]: enable_runfiles should no longer be required

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#1336]
### What happened?

At the JS BoF at BazelCon 23 someone pointed out that the enable_runfiles requirement is annoying. @gregmagolan thinks that we have made fixes for runfiles handling that should make that no longer be required.

### Version

HEAD

**Comment by ewhauser** [comment]
I can report that we have runfiles disabled and do not have any issues with the latest `rules_js` or `rules_ts`.

**Comment by alexeagle** [comment]
Fixed by https://github.com/aspect-build/rules_js/pull/1428
