### ISSUE TITLE
[FR]: Support Node 20

### ISSUE THREAD

**Issue by jestapinski** [aspect-build/rules_js#1353]
### What is the current behavior?

`rules_js` does not support Node v20

### Describe the feature

I noticed [this PR](https://github.com/aspect-build/rules_js/pull/1278) was closed which would bump `rules_nodejs` to v6, allowing folks to use Node 20. Is it possible to get this merged?

**Comment by Aghassi** [comment]
FYI what we had to do for this sort of stuff was to use `nodejs_register_toolchains` to set the version providing our own binaries. We are on rules_nodejs v5 and are not looking to update any time soon to v6 as it would be massively breaking

**Comment by jbedard** [comment]
@jestapinski I think we don't want to bump the default version at this time, maybe in 2.0. You should be able to setup your own version of rules_nodejs to do this?
