### ISSUE TITLE
[Bug]: Providers from aspect_bazel_lib does not work with Bazel 7

### ISSUE THREAD

**Issue by wielski** [aspect-build/rules_js#1404]
### What happened?

Bazel 7 added new type of prefix: double-at `@@`. Now provider should be imported as:
```
load("@@aspect_bazel_lib//lib:directory_path.bzl", "DirectoryPathInfo")
```

This causes error when trying to create `js_binary` target from `directory_path`
`Error in fail: entry_point must be a single file or a target that provides a DirectoryPathInfo`

### Version

Development (host) and target OS/architectures:
ProductName: macOS
ProductVersion: 14.0
Architecture: Apple Silicon (M2 Max)

Output of `bazel --version`:
`bazel 7.0.0`

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
```
bazel_dep(name = "aspect_rules_js", version = "1.34.1")
bazel_dep(name = "aspect_rules_ts", version = "2.1.0")
bazel_dep(name = "aspect_rules_swc", version = "1.1.0")

####### Node.js version #########
bazel_dep(name = "rules_nodejs", version = "5.8.2")
node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain(node_version = "16.14.2")

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm", dev_dependency = True)
npm.npm_translate_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)

use_repo(npm, "npm")
```

Language(s) and/or frameworks involved:
TypeScript

### How to reproduce

```shell
load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("@aspect_bazel_lib//lib:directory_path.bzl", "directory_path")

directory_path(
    name = "tsc_entrypoint",
    directory = "//:node_modules/typescript/dir",
    path = "bin/tsc",
)

js_binary(
    name = "tsc",
    data = ["//:node_modules/typescript"],
    entry_point = ":tsc_entrypoint",
    node_options = ["--max-old-space-size=4096"],
    visibility = [":__subpackages__"],
)
```

### Any other information?

Real provider of `directory_path` target from cquery is `@@aspect_bazel_lib//lib/private:directory_path.bzl%DirectoryPathInfo`:

```
bazel cquery --output starlark --starlark:expr='providers(target)' //:tsc_entrypoint     
  
INFO: Analyzed target //:tsc_entrypoint (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
{"LicenseInfo": <instance of provider LicenseInfo>, "@@aspect_bazel_lib//lib/private:directory_path.bzl%DirectoryPathInfo": struct(directory = <generated file node_modules/.aspect_rules_js/typescript@5.2.2/node_modules/typescript>, path = "bin/tsc"), "FileProvider": <unknown object com.google.devtools.build.lib.analysis.FileProvider>, "FilesToRunProvider": <unknown object com.google.devtools.build.lib.analysis.FilesToRunProvider>, "OutputGroupInfo": struct(_hidden_top_level_INTERNAL_ = depset([]))}
```

**Comment by alexeagle** [comment]
I don't think this is a rules_js bug. We generate directory_path e.g. https://github.com/aspect-build/rules_js/blob/6aa86cf0aa0e3878b41238056e9ba013781c82c1/npm/private/test/package_json_with_dashes_checked.bzl#L8 and the CI is still green.

I suspect the problem is one of:
- you need a newer version of `aspect_bazel_lib` that had some bzlmod fixes
- you don't actually want to put a double `@@` in your load statement.

**Comment by alexeagle** [comment]
Please comment if that doesn't help and you still think rules_js has a bug!
