### ISSUE TITLE
[Bug]: Error from npm_translate_lock when using pnpm.patchedDependencies

### ISSUE THREAD

**Issue by jfirebaugh** [aspect-build/rules_js#1427]
### What happened?

If you have a [`pnpm.patchedDependencies`](https://pnpm.io/package_json#pnpmpatcheddependencies) entry in `package.json`, then `npm_translate_lock` will produce an error like:

```
Error in fail: ERROR: patch_args for package @jest/environment@29.7.0 contains a strip prefix that is incompatible with a patch applied via `pnpm.patchedDependencies`.

`pnpm.patchedDependencies` requires a strip prefix of `-p1`. All applied patches must use the same strip prefix.
```

`npm_translate_lock`'s support for `pnpm.patchedDependencies` should extend to supplying a default `patch_args` value of `["-p1"]` for packages that appear in `pnpm.patchedDependencies`, since that's the format pnpm uses.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: bazel 6.1.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: rules_js-1.33.1

Language(s) and/or frameworks involved: Javascript

**Comment by kormide** [comment]
I have an old PR that does this, but I don't think we reached an agreement: https://github.com/aspect-build/rules_js/pull/837.

**Comment by jbedard** [comment]
Fixed in https://github.com/aspect-build/rules_js/pull/1694
