### ISSUE TITLE
[Bug]: Changing 'name' attribute on `npm_package` to anything but the default pak

### ISSUE THREAD

**Issue by cdelguercio** [aspect-build/rules_js#1448]
### What happened?

I have a package called "my_package", but it exists in a directory called "proto". When I set the 'name' attribute of npm package to "proto", my project builds. When I change it to anything else it complains with: 
```
ERROR: /path/BUILD.bazel:10:22: in src attribute of npm_package_store rule //:.aspect_rules_js/node_modules/@company+my-package@0.0.0: '//path/proto:proto' does not have mandatory providers: 'NpmPackageInfo'. Since this rule was created by the macro 'npm_link_all_packages', the error might have been caused by the macro implementation
ERROR: /path/BUILD.bazel:10:22: Analysis of target '//:.aspect_rules_js/node_modules/@company+my-package@0.0.0' failed
```

I assume this is because something is assuming that the npm_package target is the default target of the proto directory, but I could not figure out where. Is this an assumption that rules_js makes?

```
# This fails
npm_package(
    name = "my_package",
    srcs = [":my_src"],
    package = "@company/my_package",
    visibility = ["//visibility:public"],
)
```

```
# This succeeds
npm_package(
    name = "proto",
    srcs = [":my_src"],
    package = "@company/my_package",
    visibility = ["//visibility:public"],
)
```

### Version

Development (host) and target OS/architectures:
ubuntu

Output of `bazel --version`:
bazel 6.4.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
rules_js-1.35.0

Language(s) and/or frameworks involved:
pnpm, rules_proto_grpc

**Comment by alexeagle** [comment]
From the error message, it looks like it fails at the `npm_link_all_packages` that's referencing this package, not a problem in the BUILD file you pasted. 
`'//path/proto:proto'` is what something else is referencing. Can you find that in your repro, or post a full one so we can rerproduce?

**Comment by cdelguercio** [comment]
Ah my bad, in that run I had named my proto_library target "proto" (which is eventually what I want to do). Here is the error I get when it doesn't see any targets with the default name.

```
/path/BUILD.bazel:10:22: no such target '//path/proto:proto': target 'proto' not declared in package 'path/proto' defined by /path/BUILD.bazel (Tip: use `query "//path/proto:*"` to see all the targets in that package) and referenced by '//:.aspect_rules_js/node_modules/@company+my-package@0.0.0'
```

**Comment by alexeagle** [comment]
I still need to see more of a repro to be helpful. The error references `/path/BUILD.bazel:10:22: ` - I can't be much help without seeing that.

**Comment by cdelguercio** [comment]
@alexeagle 

https://github.com/cdelguercio/aspect_build_rules_js_issue_1448

Let me know if you need any extra info.

**Comment by cdelguercio** [comment]
@alexeagle any chance you've looked over my example repo?

**Comment by jbedard** [comment]
@cdelguercio is https://docs.aspect.build/rulesets/aspect_rules_js/docs/npm_translate_lock/#npm_package_target_name what you're looking for?

**Comment by jbedard** [comment]
Yeah it's a bit odd depending on specific names, but I think was the only way of doing it :/
