### ISSUE TITLE
Help a user who forgot to update their pnpm-lock.yaml

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#150]
We could have some repository rule to re-run `pnpm install --lockfile-only` and verify that the users file is up-to-date.

Otherwise you might add a first-party dep to your package.json and then Bazel doesn't see that change.

**Comment by cgrindel** [comment]
@alexeagle Is this addressed by #157?

**Comment by gregmagolan** [comment]
Resolved with `update_pnpm_lock` feature in `npm_translate_lock`
