### ISSUE TITLE
[Bug]: aspect_rules_js pulls in rules_buf as a dependency

### ISSUE THREAD

**Issue by csmulhern** [aspect-build/rules_js#1599]
### What happened?

It seems like this is due to the dependency on aspect_rules_lint. As far as I can tell, this is only needed for development inside aspect_rules_lint. Can we mark this as a dev_dependency? I.e.

```
bazel_dep(name = "aspect_rules_lint", version = "0.12.0", dev_dependency = True)
```

### Version

Development (host) and target OS/architectures: macOS

Output of `bazel --version`: 7.1.1

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: 1.40.1

Language(s) and/or frameworks involved:

**Comment by gregmagolan** [comment]
Yes, this should have been a dev dep in the first place. I'll put up a PR.
