### ISSUE TITLE
bug: aliased transitive dependency names do not work

### ISSUE THREAD

**Issue by alex-torok** [aspect-build/rules_js#164]
We have a dependency on plotly.js, which uses an aliased version of one of its dependencies:

https://github.com/plotly/plotly.js/blob/e0a5f13a4c9b8e2f74204499168d12b2d0bab285/package.json#L110

When adding a dependency like this, the pnpm lockfile has a version marker that matches the pnpm name:
```yaml
  /plotly.js/2.12.1:
    resolution: {integrity: sha512-XbZ3w3jSl+ihZPMXWwblmjinqbzdd+vT+3XKZpyffxmlMmTp/3vY1ewpQDuNyufUoiT0o0ekCqa80Qlzi7jwlA==}
    dependencies:
      ...
      probe-image-size: 7.2.3
      regl: /@plotly/regl/2.1.2
      regl-error2d: 2.0.12
```

The issue presents itself first as an error with iterating through the deps in transitive_dependencies.bzl:

```
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "/home/alex.torok/.cache/bazel/_bazel_alex.torok/080e6abb1a3d3304a3cf19fc0f4ef9c1/external/aspect_rules_js/npm/private/npm_translate_lock.bzl", line 319, column 33, in _impl
                lockfile = _process_lockfile(rctx)
        File "/home/alex.torok/.cache/bazel/_bazel_alex.torok/080e6abb1a3d3304a3cf19fc0f4ef9c1/external/aspect_rules_js/npm/private/npm_translate_lock.bzl", line 145, column 43, in _process_lockfile
                return translate_to_transitive_closure(lockfile, rctx.attr.prod, rctx.attr.dev, rctx.attr.no_optional)
        File "/home/alex.torok/.cache/bazel/_bazel_alex.torok/080e6abb1a3d3304a3cf19fc0f4ef9c1/external/aspect_rules_js/npm/private/transitive_closure.bzl", line 114, column 34, in translate_to_transitive_closure
                gather_transitive_closure(
        File "/home/alex.torok/.cache/bazel/_bazel_alex.torok/080e6abb1a3d3304a3cf19fc0f4ef9c1/external/aspect_rules_js/npm/private/transitive_closure.bzl", line 34, column 36, in gather_transitive_closure
                package_info = packages[utils.pnpm_name(name, version)]
Error: key "regl//@plotly/regl/2.1.2" not found in dictionary
```

I thought an easy fix could be to handle the version number differently if we detect a full path:
```diff
@@ -27,6 +29,9 @@ def _strip_peer_dep_version(version):
diff --git a/npm/private/utils.bzl b/npm/private/utils.bzl
index b05d467..2289ac3 100644
--- a/npm/private/utils.bzl
+++ b/npm/private/utils.bzl
 def _pnpm_name(name, version):
     "Make a name/version pnpm-style name for a package name and version"
+    if version.startswith("/"):
+        # Strip leading '/'
+        return version[1:]
     return "%s/%s" % (name, version)
```

This seems to address the issue seen when iterating over the transitive deps, but then I hit an issue with the link package names not being correct:

```
ERROR: /home/alex.torok/code/av/BUILD.bazel:8:22: //:store_link__regl___@plotly_regl_2.1.2__pkg: missing input file '//:store_link__regl___@plotly_regl_2.1.2__pkg'
ERROR: /home/alex.torok/code/av/BUILD.bazel:8:22: 1 input file(s) do not exist
```

Looking in my external repo directory, it appears that the plotly.js does not gain a dep on the correct link target:
```
$ rg store_link__regl___@ npm*__links/
npm__react-plotly.js__2.5.1__plotly.js_2.12.1_react_16.14.0__links/defs.bzl
85:        "store_link__regl___@plotly_regl_2.1.2__pkg",
379:        "store_link__regl___@plotly_regl_2.1.2__pkg",

npm__plotly.js__2.12.1__links/defs.bzl
78:        "store_link__regl___@plotly_regl_2.1.2__pkg",
366:        "store_link__regl___@plotly_regl_2.1.2__pkg",
648:        "store_link__regl___@plotly_regl_2.1.2__ref",
```

I got to this point and feel like the fix for this is over my head, so I'm hoping someone with more familiarity of the whole data flow from lockfile parsing to generated link targets can help out.

**Comment by alex-torok** [comment]
Sorry, just realized this is a duplicate of #86

**Comment by gregmagolan** [comment]
Thanks for the detailed summary of the issue. I started to look at just now and the code needs a bit of refactoring to support these link aliases in npm_import and npm_translate_lock. I'll pick it up again tomorrow.

**Comment by alex-torok** [comment]
Even with #171, I'm still seeing this issue when a transitive dependency is given an alias. I have a reproduction at https://github.com/alex-torok/rules_js/pull/2.

**Comment by gregmagolan** [comment]
> Even with #171, I'm still seeing this issue when a transitive dependency is given an alias. I have a reproduction at [alex-torok#2](https://github.com/alex-torok/rules_js/pull/2).

Thanks for the repo. I'll work on a fix for transitives case today.

**Comment by gregmagolan** [comment]
Cut https://github.com/aspect-build/rules_js/releases/tag/v0.12.2 which includes the fix
