### ISSUE TITLE
[FR]: Support lockfile v9 and pnpm 9

### ISSUE THREAD

**Issue by Aghassi** [aspect-build/rules_js#1652]
### What is the current behavior?

```
Error in fail: npm_translate_lock currently supports a maximum lock_version of 6.1, but found 9.0.
```

### Describe the feature

PNPM dropped v9 today and it changes the lockfile version and a few other things. I'm just filing this change as a way to track when rules_js adopts the new lockfile format and supports the new version.

https://github.com/pnpm/pnpm/releases/tag/v9.0.0

**Comment by taozhou-glean** [comment]
looks like we are beta testing [v2.0.0-alpha.0](https://github.com/aspect-build/rules_js/releases/tag/v2.0.0-alpha.0), would be nice if we can add pnpm 9 support in v2

**Comment by jbedard** [comment]
Completed for rules_js 2.0: https://github.com/aspect-build/rules_js/pull/1679

**Comment by creatifcoding** [comment]
Hey guys, I would suggest you amend the documentation per the [third paragraph](https://docs.aspect.build/rulesets/aspect_rules_js/docs/#fetch-third-party-packages-from-npm) to reflect that this issue has been closed.

**Comment by jbedard** [comment]
Thanks for the info @creatifcoding 🙏

See https://github.com/aspect-build/rules_js/pull/1882
