### ISSUE TITLE
[Bug]: version in pnpm9 lockfile is incorrectly parsed

### ISSUE THREAD

**Issue by rnons** [aspect-build/rules_js#1843]
### What happened?

Error in npm_translate_lock

```
        File "***/external/aspect_rules_js/npm/private/pnpm.bzl", line 396, column 28, in _convert_pnpm_v9_importer_dependency_map
                alias, version = version.rsplit("@", 1)
Error: too few values to unpack (got 1, want 2)
```

The lines in pnpm-lock.yaml that triggered this error:
```
      '@sentio/truffle-debugger':
        specifier: npm:@sentio/truffle-debugger@^0.0.56
        version: 0.0.56(bufferutil@4.0.8)(utf-8-validate@5.0.10)
```
I tried to print out specifier and version
```
specifier: npm:@sentio/truffle-debugger@^0.0.56 
version: 0.0.56_1408705619
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: bazel 7.2.1

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: rules_js-2.0.0-rc6

Language(s) and/or frameworks involved:

### How to reproduce

```shell
Sorry, it's a private repo
```

**Comment by jbedard** [comment]
Looks like an issue with `"pkg": "npm:pkg@1.2.3"`, where an `npm:` alias just references the package of the same name, then the resolved `version` is formatted like a non-`npm:` dep.

See https://github.com/aspect-build/rules_js/pull/1846
