### ISSUE TITLE
[Bug]: `js_run_devserver()` sandbox is broken when used with `js_library()` 

### ISSUE THREAD

**Issue by walkerburgin** [aspect-build/rules_js#1869]
### What happened?

When used together with `js_library()`, the sandbox created by `js_run_devserver()` includes symlinks which point out of the sandbox.

In a small monorepo with two packages, `//apps/foo-app` and `//pkgs/foo-lib`, the symlink in `_main/apps/foo-app/node_modules/@monorepo/foo-lib` that makes `@monorepo/foo-lib` visible to `@monorepo/foo-app` points outside of the `js_run_devserver` sandbox. So even though `//pkgs/foo-lib` files are copied into the sandbox, they aren't what the bundler sees.

### Version

Development (host) and target OS/architectures: MacOS

Output of `bazel --version`: `bazel 7.2.1` 

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: 
- `bazel_dep(name = "aspect_rules_js", version = "2.0.0-rc6")`
- `bazel_dep(name = "rules_nodejs", version = "6.2.0")`
- `bazel_dep(name = "aspect_rules_ts", version = "3.0.0-rc0")`

Language(s) and/or frameworks involved: TypeScript, Vite

### How to reproduce

See https://github.com/walkerburgin/js-run-devserver-repro

**Comment by gregmagolan** [comment]
Fixed by https://github.com/aspect-build/rules_js/pull/1872
