### ISSUE TITLE
[Bug]: js_image_layer does not include repo mapping file in app layer

### ISSUE THREAD

**Issue by jfirebaugh** [aspect-build/rules_js#1973]
### What happened?

`js_image_layer` omits the repo mapping file, so @bazel/runfiles resolution fails inside the resulting container when bzlmod is enabled.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: 7.3.1

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: 1.37.0

Language(s) and/or frameworks involved:

### How to reproduce

```shell
Via `js_image_layer`, build a container image containing a `js_binary` target with a runfiles dependency, and with bzlmod enabled. The binary can do nothing but:


const runfiles = require('@bazel/runfiles')
runfiles.resolve('<repo name>/<runfile>')
```

Run the container. It will fail with "Error: could not resolve module <repo name>/<runfile>".

If you inspect the container contents (e.g. with `dive`), you can see that the app layer has no `.repo_mapping` file.
```


### Any other information?

_No response_

**Comment by thesayyn** [comment]
This needs to be fixed in js_image_layer. However I'd like to take this opportunity and drop js_image_layers custom nodejs program
