### ISSUE TITLE
Migrate Buildbuddy repo

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#202]
context https://bazelbuild.slack.com/archives/CA31HN1T3/p1655215994490169?thread_ts=1655215797.862609&cid=CA31HN1T3

Dzintars Today at 7:09 AM
Hi all. Could some share some large'ish open source typescript SP/MP Application repository. (edited) 
Son Luong Ngoc  2 hours ago
https://github.com/buildbuddy-io/buildbuddy/tree/master/app is a good source of reference

If that app is a good reference then it should be using rules_js.
Also it's a chance to help out buildbuddy and find more bugs before our 1.0.0 launch

**Comment by alexeagle** [comment]
Started this here: https://github.com/buildbuddy-io/buildbuddy/compare/master...alexeagle:master

**Comment by thesayyn** [comment]
Current workaround for run_js_binary is to set 

```
copy_srcs_to_bin = False,
chdir = "../../../",
```

**Comment by thesayyn** [comment]
https://github.com/buildbuddy-io/buildbuddy/commit/fb7447407db590ccf28b9266540297ab6e22fb3c Fixes protobuf issue

**Comment by thesayyn** [comment]
> Or you could just carry forward on your own fork and send the PR from there, you don't need me involved :)

Sure. There is a couple of `integrity` disabled http_archives. Shall I replace them with the latest releases of rulesets?

**Comment by thesayyn** [comment]
https://github.com/buildbuddy-io/buildbuddy/pull/2143 is up.

**Comment by gregmagolan** [comment]
instead of `chdir = "../../../"` you could also set the env `BAZEL_BIN` to `.`

**Comment by gregmagolan** [comment]
that might be a bit cleaner

**Comment by alexeagle** [comment]
Need to wait for RBE before they'll let this merge.
