### ISSUE TITLE
[FR]: Allow `$(execpath output_label)` expansion in `js_run_binary`

### ISSUE THREAD

**Issue by Silic0nS0ldier** [aspect-build/rules_js#2028]
### What is the current behavior?

Only inputs from `srcs` can be referenced in `args` and `env` via variable expansion. Attempting to reference something in `outs` or `out_dirs` results in an error.

```
label '//___:___' in $(location) expression is not a declared prerequisite of this rule
```

### Describe the feature

Allow `outs` and `out_dirs` labels to be referenced in `$(execpath ___)` expansions.

**Comment by Silic0nS0ldier** [comment]
This _actually_ is a change that needs to happen in https://github.com/bazel-contrib/bazel-lib, since `js_run_binary` is a wrapper around `run_binary`.

**Comment by jbedard** [comment]
Should this FR be closed and opened there then?

**Comment by Silic0nS0ldier** [comment]
I was wrong again, this is a limitation in Bazel (`ctx.expand_location` doesn't consider outputs, unlike `genrule`'s own implementation of this). Closing, I'll open an issue in the Bazel repo.

**Comment by Silic0nS0ldier** [comment]
For anyone coming across this later: https://github.com/bazelbuild/bazel/issues/24573

**Comment by jbedard** [comment]
Thanks for the info 👍
