### ISSUE TITLE
[Bug]: Sandbox folders created by js_run_devserver are not always deleted

### ISSUE THREAD

**Issue by ancabuzatu** [aspect-build/rules_js#2033]
### What happened?

We noticed that sandbox folders created by `js_run_devserver` are not deleted and they can take quite a lot of space. If the process is interrupted by the user, then the cleanup of those folders will not performed. https://github.com/aspect-build/rules_js/blob/cd48714c7fe445a6bce6e2bcc1db36c4eefcffdf/js/private/js_run_devserver.mjs#L531-L538

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: `7.4.1`

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: `aspect_rules_js version 2.0.2`

Language(s) and/or frameworks involved:

### How to reproduce

```shell
In my case, I was running a `webpack_devserver` target and killed the process with ctrl+c.
```

**Comment by ancabuzatu** [comment]
@jbedard, I updated to the latest version of `rules_js` but it seems the issue persists, `js_run_devserver-*` folders created by `webpack_devserver` are not deleted on SIGINT. I assume that the SIGINT signal webpack receives is not propagated further, as the last printed message is "child tool process exited with code 0."

**Comment by jbedard** [comment]
Any idea if `removeSandbox` is actually being invoked?

**Comment by ancabuzatu** [comment]
Apologies for the mistake, I didn't check if the folders actually had any contents. They are empty, so it works as expected. Thank you!

**Comment by jbedard** [comment]
Do you think the directory itself should also be deleted though? 🤔
