### ISSUE TITLE
Example of qwik.js

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#214]
https://www.youtube.com/watch?v=0dC11DMR3fU

**Comment by alexeagle** [comment]
@jialipassion I chatted with @mhevery about this and he thinks someone on their team would help us out with Q's on their discord if we find anything interesting about running their dev toolchain under Bazel. Might be a fun starter project :)

**Comment by JiaLiPassion** [comment]
@alexeagle, got it, it is great, I will check the video and begin to work on it.

**Comment by alexeagle** [comment]
To be clear, the video is the sales pitch to JS devs and application owners, but doesn't go into the build system at all. Looks like there's vite so maybe it's like https://github.com/aspect-build/bazel-examples/tree/main/vue

**Comment by JiaLiPassion** [comment]
@alexeagle , got it, I will check the example repo.
