### ISSUE TITLE
js_run_binary tries to copy srcs already in output tree

### ISSUE THREAD

**Issue by duarten** [aspect-build/rules_js#226]
If, for example, one of the srcs to a `js_run_binary` rule is a generated file, then there will be a conflict:

```
(17:26:38) ERROR: file 'cocada/schemas/merged.json' is generated by these conflicting actions:
Label: //cocada/schemas:merged_gen_copy_srcs_to_bin, //cocada/schemas:merged
```

The documentation suggests the copy is conditional on the files not being in the output tree, which would be nice.

The workaround for this is to manually copy what needs to be copied and unset `copy_srcs_to_bin`.

**Comment by gregmagolan** [comment]
Under the hood, the copy is conditional, meaning if you pass an output file it won't be copied. That happens here,

https://github.com/aspect-build/bazel-lib/blob/main/lib/private/copy_to_bin.bzl#L38

There is no way for a target to know if some other target has copied a source file. However, if two actions created by two different targets are identical (same inputs & outputs) such as copying the same file to the output tree then Bazel won't consider them duplicates and not conflicting.

What kind of target is `//cocada/schemas:merged` in this case?

**Comment by gregmagolan** [comment]
That would explain it. Did you figure out a pattern that works?

**Comment by gregmagolan** [comment]
Sounds good. I'll close this issue then.

If you pipe the remaining into a `js_library` and then dep on that target, `js_library` would do the copy under the hood and may be easier to read than a copy_to_bin.
