### ISSUE TITLE
Running npm tool that dynamically loads plugins

### ISSUE THREAD

**Issue by duarten** [aspect-build/rules_js#227]
I'm trying to run an npm tool (`@graphql-codegen/cli`) that can dynamically load plugins. In `build_bazel_rules_nodejs`-land, I had the following:

```starlark
# gqlgen/BUILD.bazel
load("@npm//@graphql-codegen/cli:index.bzl", "gql_gen")

gql_gen(
    name = "gen",
    data = [
        "@npm//@graphql-codegen/schema-ast",
         # ...
    ],
    visibility = ["//visibility:public"],
)
```

A custom rule would then use this tool as the executable for `ctx.actions.run` and everything would be peachy.

With the new design, I can't follow the same approach because when the tool loads a plugin from the working directory in the output tree, there won't be a reachable `node_modules` with the plugins.

I can have the users of the tool specify the plugins, which allows me to place them in a reachable `node_modules` folder. However, The `graphql` package errors out if it is loaded from different places (`Ensure that there is only one instance of "graphql" in the node_modules directory. [...]`). The error happens because node loads the modules required by the tool relative to its location, in the runfiles under exec output dir. Later modules are loaded from the bin dir (seen with `"NODE_DEBUG": "module"`).

I thought I could get around this by writing a launcher script that imports `@graphql-codegen/cli` dynamically, but for some reason the import is still relative to the launcher. What's worse, even though I add `//:node_modules/@graphql-codegen/cli` as a dependency to the launcher, the transitive dependencies aren't there:

```starlark
js_binary(
    name = "launcher",
    data = ["//:node_modules/@graphql-codegen/cli"],
    entry_point = "launcher.mjs",
)
```

There's no local `node_modules` in the tool's directory, under runfiles (i.e., there's no `[...]/sandbox/darwin-sandbox/3298/execroot/umani/bazel-out/darwin-opt-exec-2B5CBBC6/bin/build/gqlgen/launcher.sh.runfiles/umani/node_modules/@graphql-codegen/node_modules` folder).

Are there any examples how to get such a setup to work?

**Comment by duarten** [comment]
Good to know about `packageExtensions` :) That does indeed make the plugin reachable from the execution platform output tree and would solve my problem, except that the tool [loads plugins](https://github.com/dotansimha/graphql-code-generator/blob/a11817bac5bf012715d043559dabb1b9fb34a0a9/packages/graphql-codegen-cli/src/codegen.ts#L298) from the target platform output tree. That seems to be an idiosyncrasy of the tool and fortunately they provide a hook to override that behavior. I'll work on that tonight and report back.

**Comment by duarten** [comment]
I made it work by writing a script that calls the tool directly and configures its loader. In the end, I didn't need to use the `packageExtensions`. Give the following rule:

```
js_binary(
    name = "launcher",
    data = [
        "//:node_modules/@graphql-codegen/cli",
        # Doesn't work without the following dep:
        # "//:node_modules/@graphql-codegen/schema-ast",
    ],
    entry_point = "launcher.mjs",
)
```

Regardless of the `packageExtensions` setting, if I don't directly specify the plugin as a dependency, it won't be in the execution platform output tree.

**Comment by duarten** [comment]
Closing this since it's specific to the behavior of a particular npm package and there's a solution for the problem.

**Comment by chadxzs** [comment]
@duarten I'm trying to get this same tool to work with rules_js and running into the "cannot use GraphQLObjectType XXX from another module or realm" 

Do you mind sharing your launcher script? Not sure if it will directly solve it for me but would at least help paint a full picture of what your solution to your problem was.

**Comment by duarten** [comment]
Sure! This is the launcher:

```js
// launcher.mjs

import { readFileSync } from "fs"

import { generate } from "@graphql-codegen/cli"

async function runCodeGen() {
    try {
        const contents = readFileSync(process.argv[2], { encoding: "utf8" })
        const { schemas, documents, target, config } = JSON.parse(contents)
        await generate({
            overwrite: true,
            schema: schemas,
            documents,
            generates: {
                [target]: config,
            },
        })
    } catch (e) {
        console.error(e)
        process.exit(1)
    }
}

runCodeGen()
```

This is the build file:

```starlark
# BUILD.bazel

load("@aspect_rules_js//js:defs.bzl", "js_binary")

# Use a launcher to get all the transitive dependencies of the plugins.
js_binary(
    name = "launcher",
    data = [
        "//:node_modules/@graphql-codegen/add",
        "//:node_modules/@graphql-codegen/cli",
        "//:node_modules/@graphql-codegen/introspection",
        "//:node_modules/@graphql-codegen/named-operations-object",
        "//:node_modules/@graphql-codegen/schema-ast",
        "//:node_modules/@graphql-codegen/typescript",
        "//:node_modules/@graphql-codegen/typescript-operations",
        "//:node_modules/@graphql-codegen/typescript-react-query",
    ],
    entry_point = "launcher.mjs",
    visibility = ["//visibility:public"],
)
```

And this is the rule:

```starlark
# index.bzl

"GraphQL code generation macro"

load("@aspect_rules_js//js:defs.bzl", "js_run_binary")

def _gqlgen_params_impl(ctx):
    params = {
        "config": json.decode(ctx.attr.config),
        "documents": [],
        "schemas": [],
        "target": ctx.attr.target,
    }
    for s in ctx.files.schemas:
        list = params["documents" if s.path.find("-ops") >= 0 else "schemas"]
        list.append("../../../%s" % s.path)
    ctx.actions.write(
        output = ctx.outputs.out,
        content = json.encode(params),
        is_executable = False,
    )
    return [DefaultInfo(files = depset(direct = [ctx.outputs.out]))]

_gqlgen_params = rule(
    implementation = _gqlgen_params_impl,
    attrs = {
        "config": attr.string(mandatory = True),
        "out": attr.output(mandatory = True),
        "schemas": attr.label(allow_files = [".graphql"]),
        "target": attr.string(mandatory = True),
    },
)

def gqlgen(name, schemas, out, config, **kwargs):
    """GraphQL code generation

    A single file is generated from the specified schemas and configuration.

    Args:
        name: The name of the rule
        schemas: The schema and operation GraphQL files
        out: The name of the generated file
        config: The configuration for the generated file as a dict
        **kwargs: Remaining arguments passed to the inner `js_run_binary` rule
    """
    if type(config) != type(dict()):
        fail("the config attribute must be a dict")
    params = name + "_params"
    _gqlgen_params(
        name = params,
        schemas = schemas,
        target = "%s/%s" % (native.package_name(), out),
        config = json.encode(config),
        out = params + ".json",
    )
    js_run_binary(
        name = name,
        srcs = [schemas, params],
        outs = [out],
        args = ["$(rootpath %s)" % params],
        tool = "//build/gqlgen:launcher",
        # Uncomment to debug @graphql-codegen/cli loading plugins:
        # env = {
        #     "JS_BINARY__LOG_DEBUG": "1",
        #     "JS_BINARY__LOG_INFO": "1",
        #     "NODE_DEBUG": "module",
        # },
        **kwargs
    )
```

Example usage:

```starlark
gqlgen(
    name = "generate_types",
    out = "generated-types.ts",
    config = {
        "config": {
            "avoidOptionals": True,
            "nonOptionalTypename": True,
        },
        "plugins": [
            {
                "add": {
                    "content": "/* eslint-disable */",
                },
            },
            "typescript",
        ],
    },
    schemas = ":schema_files",
)
```

**Comment by chadxzs** [comment]
Thanks @duarten that worked for us as well. 🍻

**Comment by patrick-steadman** [comment]
@duarten @gregmagolan would you both be open to me creating a PR with the example in https://github.com/aspect-build/bazel-examples ? will credit you ofc @duarten

**Comment by ptsteadman** [comment]
@duarten @gregmagolan would you be open to me opening a PR to add an example for this in https://github.com/aspect-build/bazel-examples ? would credit @duarten ofc :)

**Comment by gregmagolan** [comment]
@ptsteadman That would be great to get a contribution there. Thanks for the offer.
