### ISSUE TITLE
Default mnemonic for bin contains illegal characters

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#235]
Bazel's mnemonics are typically CamelCase. We currently replace `-` with `_` in https://github.com/aspect-build/rules_js/blob/08705237cd7525fc674c51072cbbb16fba325a93/npm/private/npm_import.bzl#L238 but this is still illegal:

`Error in run: mnemonic must only contain letters and/or digits, and have non-zero length, was: "react_scripts"`

Ideally we should convert to CamelCase, though I don't know of an existing starlark utility for that.

**Comment by alexeagle** [comment]
this is technically a breaking change, should try to get it in before 1.0.0 final

**Comment by alex-torok** [comment]
FYI - This was fixed in #242

**Comment by alexeagle** [comment]
Thanks @alex-torok !!
