### ISSUE TITLE
Adding @types/node removes access to Jest

### ISSUE THREAD

**Issue by paullewis** [aspect-build/rules_js#245]
Hey,

I could be holding things wrong by doing it this way (and I couldn't think of a better summary - apologies for that!), but say I have the following `package.json`:

```json
{
  "name": "repro",
  "version": "1.0.0",
  "dependencies": {
    "jest": "28.1.1"
  }
}
```

In the root `BUILD.bazel` file I then link in the node_modules:

```
load("@npm//:defs.bzl", "npm_link_all_packages")
npm_link_all_packages(name = "node_modules")
```

Now I can access Jest in other `BUILD.bazel` files. So let's assume I have `//src` with:

```
load("@npm__jest__28.1.1//:package_json.bzl", "jest_test")

jest_test(
  name = "jest",
)
```

Granted this isn't populated with anything runnable, but it should build. And it does. When I run `bazel build //src:jest` that works.

However, if I now run `pnpm install @types/node` and try the build again it fails:

```
$ bazel build //src:jest
ERROR: Skipping '//src:jest': error loading package 'src': Unable to find package for @npm__jest__28.1.1//:package_json.bzl: The repository '@npm__jest__28.1.1' could not be resolved: Repository '@npm__jest__28.1.1' is not defined.
WARNING: Target pattern parsing failed.
ERROR: error loading package 'src': Unable to find package for @npm__jest__28.1.1//:package_json.bzl: The repository '@npm__jest__28.1.1' could not be resolved: Repository '@npm__jest__28.1.1' is not defined.
```

Looking in the repo's `external` dir it looks as though the `@npm__jest__28.1.1` dir has been removed by virtue of adding in the `@types/node`. Removing `@types/node` fixes the issue, and I'm not at all sure why.

**Comment by gregmagolan** [comment]
My guess from the description is that jest has a peer dep on @types/node so by adding it the version of jest in the lockfile then includes its peer dep.

The simpler load statement which allows you to omit the version of jest that pnpm chooses in the lockfile looks like this

```
load("@npm//:jest/package_json.bzl", "jest_test")
```

(assuming the package.json is in the root of the WORKSPACE which from the sounds of it is where you are linking jest)

**Comment by paullewis** [comment]
Hmm, yes, so the change to the pnpm lockfile is:

```diff
- /jest/28.1.1:
+ /jest/28.1.1_@types+node@18.0.0:
    resolution: {integrity: sha512-qw9YHBnjt6TCbIDMPMpJZqf9E12rh6869iZaN08/vpOGgHJSAaLLUn6H8W3IAEuy34Ls3rct064mZLETkxJ2XA==}
    engines: {node: ^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0}
    hasBin: true
    peerDependencies:
      node-notifier: ^8.0.1 || ^9.0.0 || ^10.0.0
    peerDependenciesMeta:
      node-notifier:
        optional: true
    dependencies:
      '@jest/core': 28.1.1
      '@jest/types': 28.1.1
      import-local: 3.1.0
-      jest-cli: 28.1.1
+      jest-cli: 28.1.1_@types+node@18.0.0
    transitivePeerDependencies:
      - '@types/node'
      - supports-color
      - ts-node
    dev: false
```

I appreciate rules_js is just picking up the pnpm info and using that to generate the BUILD rules, so presumably this is actually a bug in pnpm in some way and just happens to be manifesting here?

**Comment by gregmagolan** [comment]
That is an odd once since jest-cli@28.1.1 doesn't have a peerDep on @types/node. https://unpkg.com/jest-cli@28.1.1/package.json

The version notation `28.1.1_@types+node@18.0.0` is usually used when there are peerDependencies to indicate which version of the peer is resolved.

If you stick with loading the bins from the `npm_translate_lock` repository (typically `@npm`) then you don't have to specify the virtual store version since you're selecting the resolved direct dependency version in this case,

```
load("@npm//:jest/package_json.bzl", jest_bin = "bin")
jest_bin.jest_test(...)
```

**Comment by gregmagolan** [comment]
Ohh. It's probably coming from the `"@types/node": "*"` deps in https://unpkg.com/@jest/types@28.1.1/package.json which is in the transitive closure.

pnpm is just very explicit in the package versions lockfile about transitive versions for any given package/version in the virtual store.

**Comment by paullewis** [comment]
Ah, I'm relatively new to pnpm so I likely don't have the right mental model for it. Thanks for helping me understand. It does seem that if I go via the non-versioned load statement everything WAI - plus it's neater to just pull the dependency without the version number in it, I think.

Thanks so much for the help!
