### ISSUE TITLE
Support migration without installing pnpm, node, etc. on host

### ISSUE THREAD

**Issue by gonzojive** [aspect-build/rules_js#247]
I assume rules_js has access to node and pnpm binaries through bazel targets. Could `main/docs/migrate.md` be updated to mention the `bazel run` command that's equivalent to `pnpm install` based on a local pnpm installation?

Part of the beauty of bazel is there is often no need to install random development tools on a workstation, so I prefer `bazel run` wherever possible.

**Comment by jbedard** [comment]
rules_js only reads the pnpm lock file and actually has no pnpm binary. The lockfile is also what makes pnpm deterministic which is essential.

**Comment by alexeagle** [comment]
https://github.com/bazelbuild/rules_nodejs/blob/stable/docs/repositories.md#nodejs_host documents where the tooling lives

**Comment by lummax** [comment]
> bazel run -- @nodejs_host//:npx_bin pnpm@latest i --lockfile-only

unfortunately this does not work on a system where no `node` exists in the `PATH`.

```
bazel run -- @nodejs_host//:npx_bin pnpm@latest i --lockfile-only
INFO: Invocation ID: 6212bc2c-dfdc-4e76-8183-61407f0912a2
INFO: Analyzed target @nodejs_host//:npx_bin (0 packages loaded, 3 targets configured).
INFO: Found 1 target...
Target @nodejs_linux_amd64//:bin/nodejs/lib/node_modules/npm/bin/npx-cli.js up-to-date (nothing to build)
INFO: Elapsed time: 0.115s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
/usr/bin/env: ‘node’: No such file or directory
```

**Comment by pedrobarco** [comment]
Any updates on this issue? Looks like #236 was closed without an actual fix
