### ISSUE TITLE
Example of Angular with ngc/ts_project

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#263]
In contrast to the architect example we've got already, this should show a decomposition to smaller ts_project compilation units.

**Comment by alexeagle** [comment]
https://github.com/arobinson/rules-js-ngc is a starting point. it currently fails because the relative imports don't resolve.

**Comment by jbedard** [comment]
Done: https://github.com/aspect-build/bazel-examples/pull/51
