### ISSUE TITLE
Bug: `file:` resolutions aren't supported

### ISSUE THREAD

**Issue by paullewis** [aspect-build/rules_js#268]
Hey there,

If you have `resolutions` in your `package.json` like so:

```json
{
  "resolutions": {
    "ts-log": "file:local/ts-log"
  }
}
```

And then you have a package that uses – say – `ts-log` (as per the above), like `@graphql-codegen/cli`, a build will fail because of the `:` in the path.

```ERROR: app/BUILD.bazel:15:22: //:.aspect_rules_js/node_modules/@graphql-codegen/cli/2.6.4_@types+node@18.0.0/pkg: invalid label ':.aspect_rules_js/node_modules/ts-log/file:local/ts-log/ref' in dict key element: invalid target name '.aspect_rules_js/node_modules/ts-log/file:local/ts-log/ref': target names may not contain ':'```

I'm aware #167 was recently fixed, but I'm seeing this in `rules_js-1.0.0-rc.1` which AFAICT was released afterwards.

Thanks!

**Comment by gregmagolan** [comment]
Hmmm. I didn't try having `file:` path in resolutions in that fix, just in dependencies. I will TAL when I have some time this week.

**Comment by gregmagolan** [comment]
Tried to create a repo but not sure how to repro this one. Could you please make a minimal repro?

**Comment by paullewis** [comment]
Absolutely! https://github.com/paullewis/repro-rules-js-issue-268 has a `resolutions` property set in the `package.json` and building the `//src` target triggers the issue.

**Comment by gregmagolan** [comment]
Sweet. I see the problem now. It's the transitive case. Should be a relatively easy fix.
