### ISSUE TITLE
Feature: allow for a way to set environment variables for the lifecycle hook actions

### ISSUE THREAD

**Issue by lummax** [aspect-build/rules_js#269]
Some `npm` dependencies allow for configuration via environment variables. See https://sharp.pixelplumbing.com/install#prebuilt-sharp-binaries as an example.

It would be great to be able to inject environment variables into the generated `npm_import()` calls so that a global `--action_env` is not necessary.

**Comment by JiaLiPassion** [comment]
@lummax , I am implementing this feature now, it seems `sharp` will install the `prebuilt binary` into `npm_cache` folder, could you share your repo to describe how you `install` and `use` sharp with `rules_js` bazel rule? 

Thank you.

**Comment by lummax** [comment]
hey @JiaLiPassion great news!

I've setup https://github.com/lummax/bazel-rules-js-sharp-example as an example. This currently only works because of a workaround as described in https://github.com/aspect-build/rules_js/issues/217#issuecomment-1170098799.

It would be great of the environment variable injection would be subject to `$(location)` expansion so that we can download the prebuild files using `http_file()` and pass them into the `sharp` setup.

**Comment by JiaLiPassion** [comment]
@lummax , thank you, I have implemented a PR to support this feature.
