### ISSUE TITLE
Feature: allow for a way to add tags for the lifecycle hook actions

### ISSUE THREAD

**Issue by lummax** [aspect-build/rules_js#270]
Some `npm` packages want to download prebuild binaries during their lifecycle actions. See for example https://sharp.pixelplumbing.com/install#prebuilt-binaries.

When running `bazel` with `--sandbox_default_allow_network=false` these downloads will fail. It would be great to be able to add `tags` to the generated `npm_import()` calls.

**Comment by JiaLiPassion** [comment]
@lummax , could you give me an example about what kind of tags you want to set, I want to create test cases based on your sample, thanks.

**Comment by lummax** [comment]
This is mainly about passing `tags=["requires-network"]`.
