### ISSUE TITLE
npm_translate_lock: accept package-lock.json / yarn.lock files and run `pnpm import`

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#272]
From @jfirebaugh, a suggestion that I like a lot:

- Users don't have to be re-trained, they continue to use npm/yarn locally to install packages and update the lockfile
- Bazel, via rules_js, translates the lockfile as one more subprocess spawn in our repository rule
- This means that Bazel behavior can be different from local, due to hoisting bugs and undeclared dependency edges

We just need to ensure that `pnpm import` is fast enough and hermetic/deterministic.

Effectively, under Bazel you're accepting the pnpm migration, but end-users don't have to know about that yet. So this has different tradeoffs from @gregmagolan 's idea of running `npm install`/`yarn install` as a transition to rules_js.

**Comment by gregmagolan** [comment]
Done in #276
