### ISSUE TITLE
Documentation for js_run_binary suggests loading a private file

### ISSUE THREAD

**Issue by jfirebaugh** [aspect-build/rules_js#273]
https://docs.aspect.build/aspect-build/rules_js/v1.0.0-beta.0/docs/js_run_binary-docgen.html#js_run_binary

> Example usage (generated)
> ```
> load("@aspect_rules_js//js/private:js_run_binary.bzl", "js_run_binary")
> ...
> ```

This should read `load("@aspect_rules_js//js:defs.bzl", "js_run_binary")` instead.

**Comment by lummax** [comment]
The examples https://docs.aspect.build/aspect-build/rules_js/v1.0.0-beta.0/docs/js_binary-docgen.html also recommends `  enable_runfiles = false` which should be `False` (actually this attribute is not needed if the non-private version is used).

**Comment by gregmagolan** [comment]
This looks like a docsite issue @alexeagle @kormide

**Comment by gregmagolan** [comment]
![Screen Shot 2022-07-13 at 4 59 41 PM](https://user-images.githubusercontent.com/520826/178856893-f8ff1c5d-8e92-48c1-b202-19a46fa559f7.png)
![Screen Shot 2022-07-13 at 4 59 45 PM](https://user-images.githubusercontent.com/520826/178856898-ce11929e-226a-44ec-a19c-be9bbf3533e5.png)

**Comment by kormide** [comment]
Fixed.
