### ISSUE TITLE
launching js_binary .sh fails when launched from sh_binary

### ISSUE THREAD

**Issue by jbedard** [aspect-build/rules_js#285]
It seems invoking the `sh_binary` does not generate the `.runfiles` of the `js_library`. Invoking or building the `js_library` first creates the `.runfiles`, then the `sh_binary` works going forward.

Note `sh_test` does correctly generate the `.runfiles`.

Repro: https://github.com/jbedard/rules_js/commit/264a0596e62f3e3012dd79347288750577cfa1b4
```
bazel run //examples/js_binary:test10
FATAL: aspect_rules_js[js_binary]: RUNFILES environment variable is not set

bazel run //examples/js_binary:bin10-js_binary
bazel run //examples/js_binary:test10
```
(the second `test10` works after running the `js_binary` correctly)

Another example: https://github.com/pjjw/rules_nodejs_1451/tree/7a816e786de504d7687d3a0dd0ae97729749710c

**Comment by gregmagolan** [comment]
From this thread on Bazel slack: https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1657694352729829
