### ISSUE TITLE
Port @bazel/jasmine rule to rules_js

### ISSUE THREAD

**Issue by gregmagolan** [aspect-build/rules_js#296]
The rules_nodejs rule is a custom rule that adds sharding support. We should port this over to rules_js to a new rules_jasmine repository for users that are migrating and relying on sharding.

For users not relying on sharding, Doug Parker has a working simple macro around the generated bin js_test for jasmine here, https://github.com/dgp1130/rules_prerender/commit/08b4c5bac20f480b7b7c4039a4d750db51a00267.

**Comment by thesayyn** [comment]
closing as completed.
