### ISSUE TITLE
Consider documenting interactions with IDE tooling.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [aspect-build/rules_js#316]
IDE's have some tools that have a certain set of assumptions that a project using `rules_js` does not fulfill.  For the most part, they can be worked around in various ways, but it can be a lot of trial-and-error that bumps up against the specifics of this project and ends up with unintuitive solutions.  In my case, VSCode doesn't pick up on TypeScript types, but the intuitive workaround was to use `compilerOptions.path` in `tsconfig.json` to map imports to `bazel-bin/node_modules`.  But because the lazy linking appears to only apply to direct dependencies and not transitive ones, some of the types would be incomplete.  I ended up getting a workable solution (install a "node_modules" folder independent of Bazel) from a comment on #105, but it is not a documented solution.  Would it be reasonable to document this pattern, or adding an example at https://github.com/aspect-build/bazel-examples to point to?

**Comment by alexeagle** [comment]
I added this section
https://github.com/aspect-build/rules_js/blob/main/docs/faq.md#making-the-editor-happy
do you think that covers it?

**Comment by wtgtybhertgeghgtwtg** [comment]
I believe so. although the lazy loading of dependencies might be worth mentioning.  Thank you.
