### ISSUE TITLE
js_image e2e example: bazel run //:image doesn't produce any output

### ISSUE THREAD

**Issue by mvukov** [aspect-build/rules_js#361]
All I get is:
```
✎ bazel run //:image
INFO: Analyzed target //:image (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:image up-to-date:
  bazel-out/k8-fastbuild-ST-4a519fd6d3e4/bin/image-layer.tar
INFO: Elapsed time: 0.611s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Loaded image ID: sha256:265443fac79623f405f296ad480924935afc102b647a739c45578654c051901c
Tagging 265443fac79623f405f296ad480924935afc102b647a739c45578654c051901c as bazel:image
```
bazel: 5.2.0
os: Ubuntu 20.04
rules_js: f6e214c1964a494353414a29790223ff203b4faa

On the other hand, `bazel run //:main` produces some textual output.

**Comment by alexeagle** [comment]
Like rules_docker language images, "run" on a js_image just loads it into your docker daemon. So I think this is working as intended. Maybe needs a doc update to clarify expectations?

**Comment by mvukov** [comment]
Indeed, some docs would clarify this. FWIW, a [nodejs_image](https://github.com/bazelbuild/rules_docker#nodejs_image) executes the given nodejs_binary target when one invokes `bazel run //path/to:nodejs_image_target`.

**Comment by alexeagle** [comment]
Yeah, thanks I had this backwards, it's https://github.com/bazelbuild/rules_docker/blob/master/docs/container.md#container_image which loads into the daemon on `run` and the language-specific rules which execute the container.

**Comment by mvukov** [comment]
:+1: Thanks for the reference. I typically use app_layer instead of container_image -- app_layer is executable by default.
