### ISSUE TITLE
Add workspace snippet for bzlmod usage

### ISSUE THREAD

**Issue by kormide** [aspect-build/rules_js#371]

**Comment by alexeagle** [comment]
I guess this is blocked on having a better story for how dependencies are installed, basically resolve the FIXME https://github.com/aspect-build/rules_js/blob/main/e2e/bzlmod/MODULE.bazel#L27 before we advertise bzlmod as a recommended way to install.

**Comment by alexeagle** [comment]
And now our bzlmod support was broken by bazel 5.3.0 so it's even further away.
