### ISSUE TITLE
Document "phantom" hoisted dependencies

### ISSUE THREAD

**Issue by gregmagolan** [aspect-build/rules_js#375]
See https://github.com/aspect-build/rules_js/issues/374#issuecomment-1209729290 for more context.

TL;DR is that pnpm default `hoist-pattern` of `["*"]` (https://pnpm.io/npmrc#hoist-pattern) creates a `node_modules/.pnpm/node_modules` folder that allows packages within the virtual store to resolve these hoisted packages as phantom dependencies.

We don't do this in rules_js yet. Some thought needs to be put into how this would work.

**Comment by gregmagolan** [comment]
These docs were added

**Comment by jfirebaugh** [comment]
Docs are at https://docs.aspect.build/rules/aspect_rules_js/docs/pnpm/#hoisting for anyone happening on this in the future.
