### ISSUE TITLE
attribute 'exclude_srcs_packages' is missed on npm_packages

### ISSUE THREAD

**Issue by miguelpalomera** [aspect-build/rules_js#387]
Traceback (most recent call last):
        File "/private/....c3f5902eaf83e2fcc574a67b7a2c04ab/external/aspect_rules_js/npm/private/npm_package.bzl", line 159, column 41, in _impl
                exclude_srcs_packages = ctx.attr.exclude_srcs_packages,
Error: No attribute 'exclude_srcs_packages' in attr. Make sure you declared a rule attribute with this name.
Available attributes: _action_listener, _config_dependencies, _windows_constraint, allow_overwrites, applicable_licenses, compatible_with, deprecation, exclude_srcs_patterns, exec_compatible_with, exec_properties, expect_failure, features, generator_function, generator_location, generator_name, include_external_repositories, include_srcs_packages, name, out, package, replace_prefixes, restricted_to, root_paths, srcs, tags, target_compatible_with, testonly, toolchains, transitive_configs, version, visibility

**Comment by miguelpalomera** [comment]
Starting with RC3 the above attribute is missing causing npm_package fails.
Confirmed that this attribute is missed, but also it is used internally in the _impl function

**Comment by gregmagolan** [comment]
Your WORKSPACE dependency on `aspect_bazel_lib` is likely behind what rules_js requires: https://github.com/aspect-build/rules_js/blob/59e56921652a1942520d3f16283acf4b46853c6c/js/repositories.bzl#L39.

**Comment by miguelpalomera** [comment]
Thanks a lot I will try it.

**Comment by miguelpalomera** [comment]
Just to confirm that upgrading the dependency fix the problem. Thanks a lot for your reply. A bigger thanks for this awesome rules.
