### ISSUE TITLE
Using `@bazel/runfiles` doesn't work

### ISSUE THREAD

**Issue by supercairos** [aspect-build/rules_js#406]
I'm using `bazel/runfile` to resolve files inside my build worktree and it doesn't work.
By investigating a bit deeper I realized that both envs in js_binary are not set:
```
- BAZEL_TARGET
- BAZEL_WORKSPACE
```

Setting them using the `envs` property on `js_binary` almost works!
```
    env = {
        "BAZEL_TARGET": "$(TARGET)",
        "BAZEL_WORKSPACE": "$(WORKSPACE)",
    },
```

For some reason the `TARGET` is resolved as `@//mytarget:bin` making it not work with `@bazel/runfiles`
(See here: https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/runfiles/runfiles.ts#L52)

I've now hardcoded my target and everything works well, but it seams like a big hack to me.
Hope you can fix it in a near future :)

**Comment by alexeagle** [comment]
Thanks for the link, I think that's a bug in the logic in runfiles.ts, `@//mytarget:bin` should be treated the same as `//mytarget:bin`.
We should maybe ALSO figure out why the `$(TARGET)` expands that way.

**Comment by alexeagle** [comment]
What's your bazel version? 5.3.0 just came out and it changed the label syntax a bit. I'm curious if that makes any difference.

**Comment by supercairos** [comment]
I'm using 5.2.0, will try with 5.3.0 later today :)

**Comment by supercairos** [comment]
What about the `ENV` variables not being set properly by `js_binary` ?

**Comment by supercairos** [comment]
> I'm using 5.2.0, will try with 5.3.0 later today :)

I've tested with 5.3.0 and it's still preceded with an '@': `BAZEL_TARGET: '@//proxy:bin'`

**Comment by alexeagle** [comment]
https://github.com/bazelbuild/rules_nodejs/pull/3542 plus https://github.com/aspect-build/bazel-lib/commit/b5653b6037cf993acc889cfd8430ce000a167812 should fix it, pending a release of both

**Comment by supercairos** [comment]
Perfect thanks!
