### ISSUE TITLE
add `npm_package` support for generated `package.json` file

### ISSUE THREAD

**Issue by iamricard** [aspect-build/rules_js#466]
👋🏼 we'd like to be able to define a package.json in starlark for a given `npm_package`. something like:

```starlark
npm_package(
  name = "some_package",
  package_json = {
    "name": "@myorg/some-package",
  },
  srcs = [":some_filegroup"],
)
```

to be fair we _can_ achieve this today with a `genrule`, but it breaks when we declare multiple `npm_package`s that should have different `package.json` files. for example, we have this (`ts_proto_library` is an internal rule we have that generates a group of `ts` files):

```starlark
ts_proto_library(
    name = "any_ts_proto",
    protos = ["@com_google_protobuf//:any_proto"],
)

ts_proto_library(
    name = "struct_ts_proto",
    protos = ["@com_google_protobuf//:struct_proto"],
)
```

we'd want to generate a `package.json` for each that has a different name value: `@google/protobuf/any` and `@google/protobuf/struct`. today, we can only really achieve this by putting each target into a separate bazel package which is not what we'd like.

would you be open to a PR on `npm_package` to add the feature? i'm thinking the rule could just `write_file` to `dst`.

**Comment by gregmagolan** [comment]
You could genrule multiple package.json files with different names such as `any_ts_proto_package.json` and struct_ts_proto_package.json` so that they don't collide. When they are copied into the `npm_package` you can use `replace_prefix` to rename them to just `package.json` internally. That would allow you to have multiple in the same package and you could just make a simple macro around `npm_package` that does that and looks like
```
npm_package(
  name = "some_package",
  package_json = {
    "name": "@myorg/some-package",
  },
  srcs = [":some_filegroup"],
)
```
from the user's perspective

**Comment by gregmagolan** [comment]
The happy path for users right now is to use pnpm workspaces which implies that there is a package.json per npm_package and those are in unique folders. Supporting generating one with a `package_json` attribute might be useful however even if it is not the recommended approach.

**Comment by gregmagolan** [comment]
Perhaps an example of the macro approach to start and then we can consider hoisting that the public API of npm_package in the future

**Comment by iamricard** [comment]
> When they are copied into the `npm_package` you can use `replace_prefix` to rename them to just `package.json` internally.

ah that sounds great! when you say use `replace_prefix`, is that a skylib or aspect-lib helper? i can't find anything in the `npm_package` implementation that looks like it.

**Comment by iamricard** [comment]
oh whoops i noticed now in the actual docs the `replace_prefixes` attribute 🫠 thanks for the pointer! happy to close this issue now.
