### ISSUE TITLE
Linked npm_package with root_paths are not propogated to providers?

### ISSUE THREAD

**Issue by tinganho** [aspect-build/rules_js#471]
It seems like when I use `root_paths` in `npm_package` rule. It's not being propogated when I link against it and use it in deps in `ts_project`.

```python
npm_package(
    name = "my_pkg"
    srcs = [":ts_project", ":package_json"],
    root_paths = [package_name() + "/google/protobuf", "."]
)
```
And then linkage:
```python
npm_link_package(
    name = "my_pkg_link",
    src = "//my_pkg:my_pkg",
    link = True,
)
```
And then when I use it in deps:
```python
ts_project(
    #...
    deps = ["//:my_pkg_link"]
)
```
I'm getting error here. Cannot find module etc. 

Works fine without `root_paths`.

When I debug it in "exec folder" the package files seem to have the correct paths. So, I guess it's a problem with providers?

**Comment by tinganho** [comment]
As a sidenote, `root_paths` took me hours to find out how to write correct syntax for it.

I would expect the syntax to be:
```python
root_paths = ["google/protobuf", "."]
```

**Comment by jbedard** [comment]
@tinganho do you have an example that reproduces this?

I've attempted to reproduce it but so far any tests I've written seem to work just fine. Maybe you can edit my example to reproduce it? See https://github.com/jbedard/rules_js/commit/6b5e14846c308e888a6fb725051efc311218308d

**Comment by tinganho** [comment]
@jbedard I'm no longer experiencing this. I think you can close it.
