### ISSUE TITLE
Nx Support?

### ISSUE THREAD

**Issue by samhowes** [aspect-build/rules_js#476]
I just stumbled upon Nx: https://nx.dev/ 

Are there any plans for any integrations/migrations/support for Nx?

**Comment by jbedard** [comment]
Which part of Nx are you thinking would be integrated?

Nx seems to be primarily just an enhanced cli for angular, unrelated to the actual compilation that bazel would be doing.

**Comment by gregmagolan** [comment]
No immediate plans. We're friends with Nx founders and they have considered supporting Bazel in the past but rules_nodejs wasn't good enough to make it worth while. To properly support any monorepo with rules_js the first thing to build is BUILD file generation which is a project we already have underway. Once that is done it opens the door to integrating with monorepo tooling such as Nx.

**Comment by samhowes** [comment]
I'm new to rules_js and new to Nx - I was asking because WebStorm was suggesting a migration to Nx for my angular project. Thank you for you explanations. 

Closing issue as my question is answered.
