### ISSUE TITLE
`npm_import` failure due to duplicate JSON key

### ISSUE THREAD

**Issue by Silic0nS0ldier** [aspect-build/rules_js#493]
Technically JSON allows duplicate keys, or at least the parser in NodeJS does.

The package `@codeceptjs/helper` v1.0.2 has duplicate keys in its `package.json` (specifically `scripts`), causing Rules JS to fail to parse.

From the answers on https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object originally this was left ambiguous. As of ECMA-262 behaviour of `JSON.parse` was clarified here, it specifies that the last one wins.

Gross that a package has turned up (most likely be accident) which relies on this. I'll leave it up to maintainers to decide is this is a bug or "ecosystem alignment feature".

## Workaround

```starlark
# WORKSPACE.bazel
...
npm_translate_lock(
    ...
    patch_args = {
        "@codeceptjs/helper@1.0.2": ["-p1"]
    },
    patches = {
        "@codeceptjs/helper@1.0.2": ["//:patches/@codeceptjs__helper@1.0.2.patch"]
    },
    ...
)
...
```
```patch
patches/@codeceptjs__helper@1.0.2.patch
Generated using pnpm's patch commands.
diff --git a/package.json b/package.json
index 406e3cd21d59b4c77be0a27f5e75dc72a6064262..168861f06bc9cd21579ecfbe035a4fbea30be4d5 100644
--- a/package.json
+++ b/package.json
@@ -7,7 +7,8 @@
     "helper.js"
   ],
   "scripts": {
-    "test": "echo \"Error: no test specified\" && exit 1"
+    "test": "echo \"Error: no test specified\" && exit 1",
+    "docs": "documentation readme helper.js -s API"
   },
   "repository": {
     "type": "git",
@@ -16,9 +17,6 @@
   "keywords": [
     "codeceptjs"
   ],
-  "scripts": {
-    "docs": "documentation readme helper.js -s API"
-  },
   "author": "Michael Bodnarchuk @davert",
   "license": "ISC",
   "bugs": {
```
```json
// package.json, optional
{
    ...
    "pnpm": {
        "patchedDependencies": {
            "@codeceptjs/helper@1.0.2": "patches/@codeceptjs__helper@1.0.2.patch"
        },
    },
    ...
}
```

**Comment by Silic0nS0ldier** [comment]
This probably has some overlap with #483, regarding how JS handles JSON vs. everything else.

**Comment by fredrik-w** [comment]
I hit the same issue with bl@4.0.3, but thankfully they released 4.0.4 which fixes it. Though, for me, it was a transitive dependency so I had to override it in package.json:

```json
  "resolutions": {
    "bl": "4.0.4"
  }
```


If you have a newer version of npm it's called [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) now. This, of course, only helps if there is a fixed version published afterwards.

**Comment by cgrindel** [comment]
@Silic0nS0ldier Has anyone proffered a fix to `@codeceptjs/helper` to remove the duplicate keys?

**Comment by jbedard** [comment]
This is due to https://github.com/bazelbuild/bazel/issues/15605 and it needs to be fixed there. See also: https://github.com/aspect-build/rules_js/issues/148

For now the only solution is patching the package.json like you've done.
