### ISSUE TITLE
Execute js_binary from the working directory it's called from?

### ISSUE THREAD

**Issue by gregjacobs** [aspect-build/rules_js#525]
Hey guys,

I'm trying to use `js_binary` in conjunction with `bazel run` to build and run an executable that operates on files relative to the current working directory in my terminal. 

However, the current working directory (`process.cwd()`) inside the `entry_point` script ends up being deep inside the runfiles directory rather than where I ran the program from. Is there a reason for this? It seems it would make sense that the cwd should be where the program is executed from. Or is there a way to make this happen that I'm not seeing in the docs?

Thanks,
Greg

**Comment by jbedard** [comment]
Any `bazel run` will have the cwd in the runfiles. It looks like `BUILD_WORKING_DIRECTORY` would be what you're looking for? See https://bazel.build/docs/user-manual

**Comment by gregjacobs** [comment]
@jbedard Ah, thank you, definitely what I'm looking for! This env var might be a good addition to docs for any other users that might not be familiar.

Thanks again,
Greg
