### ISSUE TITLE
Support for package.json's with tarball URL with npm_translate_lock?

### ISSUE THREAD

**Issue by rc-glean** [aspect-build/rules_js#531]
See issue title, are tarball URLs supported with npm_translate_lock?

I'm using yarn classic (v1.22.19) if that matters.

Input/output:

```
bazel build //:node_modules

ERROR: Traceback (most recent call last):
	File "/Users/ray/workspace/$privaterepo", line 1154, column 17, in <toplevel>
		npm_repositories()
	File "/private/var/tmp/_bazel_ray/0a45558874bc1f97bcaab4f86b774d47/external/npmaspect/repositories.bzl", line 110733, column 15, in npm_repositories
		npm_import(
	File "/private/var/tmp/_bazel_ray/0a45558874bc1f97bcaab4f86b774d47/external/aspect_rules_js/npm/npm_import.bzl", line 596, column 16, in npm_import
		_npm_import(
Error in repository_rule: invalid repository name '@npmaspect__d3-org-chart__at_gitpkg.vercel.$privaterepo?1234abcprivaterepohash': workspace names may contain only A-Z, a-z, 0-9, '-', '_' and '.'
ERROR: error loading package '': Encountered error while reading extension file 'ts/repositories.bzl': no such package '@aspect_rules_ts//ts': error loading package 'external': Could not load //external package
INFO: Elapsed time: 5.771s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

My tarball looks like this public repo example https://github.com/hashintel/hash/blob/9c172957d1477d40aca55a8c3949d9ab93227baf/packages/hash/api/package.json#L26

FWIW, it looks like links to commits work well from [this angular example](https://github.com/angular/vscode-ng-language-service/blob/f5f7bb1203ceefab96e9c5ea8fa2162bed868f2b/package.json#L235). Seems like only tarballs have an issue

**Comment by gregmagolan** [comment]
Thanks for the report. Should be easy to fix as the error is just that the generated repository name has invalid characters. Just need to update the repository name generation string sanitizer.

**Comment by rc-glean** [comment]
Whoah that was fast. Thank you so much

**Comment by gregmagolan** [comment]
No problem. It was an easy one. Releasing v1.5.2 which will include the fix.
