### ISSUE TITLE
ERROR: in verify_node_modules_ignored

### ISSUE THREAD

**Issue by Jaskerv** [aspect-build/rules_js#547]
I had this working yesterday but now its not working.

Getting this error:
```
ERROR: no such package '@npm//': 
ERROR: in verify_node_modules_ignored:
pnpm install will create nested node_modules, but not all of them are ignored by Bazel.
We recommend that all node_modules folders in the source tree be ignored,
to avoid Bazel printing confusing error messages.

Either add line(s) to //:.bazelignore:

node_modules

or disable this check by setting 'verify_node_modules_ignored = None' in `npm_translate_lock(name = "npm")
```

My .bazelignore:
```
node_modules
bazel-out
bazel-bin
bazel-next.js
bazel-testlogs
```

My WORKSPACE.bazel:
```
http_archive(
    name = "aspect_rules_js",
    sha256 = "515277ae357e62f52e29e0bfb60b73d2d062b8d00d21351d31f37c5bb275d4f5",
    strip_prefix = "rules_js-1.5.3",
    url = "https://github.com/aspect-build/rules_js/archive/refs/tags/v1.5.3.tar.gz",
)

http_archive(
    name = "aspect_rules_swc",
    sha256 = "313307136cb6369f3c9d2992209c1e354b3e2c9989877ee67c688917320fba1f",
    strip_prefix = "rules_swc-0.17.1",
    url = "https://github.com/aspect-build/rules_swc/archive/refs/tags/v0.17.1.tar.gz",
)

http_archive(
    name = "aspect_rules_ts",
    sha256 = "743f0e988e4e3f1e25e52c79f9dc3da1ddd77507ae88787ae95b4e70c537872b",
    strip_prefix = "rules_ts-1.0.0-rc4",
    url = "https://github.com/aspect-build/rules_ts/archive/refs/tags/v1.0.0-rc4.tar.gz",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@rules_nodejs//nodejs:repositories.bzl", "DEFAULT_NODE_VERSION", "nodejs_register_toolchains")

# Fetches the rules_ts dependencies.
# If you want to have a different version of some dependency,
# you should fetch it *before* calling this.
# Alternatively, you can skip calling this function, so long as you've
# already fetched all the dependencies.
load("@aspect_rules_ts//ts:repositories.bzl", "rules_ts_dependencies")

rules_ts_dependencies(
    ts_version_from = "//:package.json",
    ts_integrity = "sha512-QCh+85mCy+h0IGff8r5XWzOVSbBO+KfeYrMQh7NJ58QujwcE22u+NUSmUxqF+un70P9GXKxa2HCNiTTMJknyjQ==",
)

nodejs_register_toolchains(
    name = "nodejs",
    node_version = DEFAULT_NODE_VERSION,
)

load("@aspect_rules_js//npm:npm_import.bzl", "npm_translate_lock")

npm_translate_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)

load("@npm//:repositories.bzl", "npm_repositories")

npm_repositories()

# Fetches the rules_swc dependencies.
# If you want to have a different version of some dependency,
# you should fetch it *before* calling this.
# Alternatively, you can skip calling this function, so long as you've
# already fetched all the dependencies.
load("@aspect_rules_swc//swc:dependencies.bzl", "rules_swc_dependencies")

rules_swc_dependencies()

# Fetches a pre-built Rust-node binding from
# https://github.com/swc-project/swc/releases.
# If you'd rather compile it from source, you can use rules_rust, fetch the project,
# then register the toolchain yourself. (Note, this is not yet documented)
load("@aspect_rules_swc//swc:repositories.bzl", "swc_register_toolchains")

swc_register_toolchains(
    name = "swc",
    swc_version = "v1.2.141",
)
```

**Comment by gregmagolan** [comment]
That is surprising. That code that checks the bazelignore is really straight forward. Your bazelignore looks a lot like this one, https://github.com/aspect-build/bazel-examples/blob/main/next.js/.bazelignore.

Is the bazelignore you're referring to in the root of your WORKSPACE or are you working in a subdirectory?

Setting `verify_node_modules_ignored = None,` in npm_translate_lock in your WORKSPACE should make the error go away tho I'm curious how you got into this state.

**Comment by Jaskerv** [comment]
> That is surprising. That code that checks the bazelignore is really straight forward. Your bazelignore looks a lot like this one, https://github.com/aspect-build/bazel-examples/blob/main/next.js/.bazelignore.
> 
> Is the bazelignore you're referring to in the root of your WORKSPACE or are you working in a subdirectory?
> 
> Setting `verify_node_modules_ignored = None,` in npm_translate_lock in your WORKSPACE should make the error go away tho I'm curious how you got into this state.

Yeah my `.bazelignore` is in my root folder and I am following the nextjs example. When I tried setting it to `None` the first time it didn't work but I guess its working now 🎉 

Any methods of debugging the original issue? I'm curious what the cons are to setting it to `None`.

**Comment by gregmagolan** [comment]
To debug you could inject some print statements into the rules_js code. You can find it under `$(bazel info output_base)/external/aspect_rules_js`:

```
$ ls $(bazel info output_base)/external/aspect_rules_js
BUILD.bazel		MODULE.bazel		docs			js			platforms		renovate.json
CONTRIBUTING.md		README.md		e2e			npm			pnpm-lock.yaml		workspace_status.sh
LICENSE			WORKSPACE		examples		package.json		pnpm-workspace.yaml
```

Setting break points and stepping through starlark code is not possible as there are no tools for this but with a few print statements you could get to bottom of where the code has gone wrong.

The relevant code to inspect is here: https://github.com/aspect-build/rules_js/blob/42b19d19611d307e959aab957a5c80da5d53d753/npm/private/npm_translate_lock.bzl#L584

Otherwise if you can come up with a minimal repro then I could TAL.

**Comment by Jaskerv** [comment]
>Otherwise if you can come up with a minimal repro then I could TAL.

That would be great! Here is a minimal set up of the rules I currently have, https://github.com/Jaskerv/simple-rules-js.

I'll also look into those print statements.

**Comment by Jaskerv** [comment]
```
❯ bazel version
Bazelisk version: development
Build label: 5.3.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 19 18:22:12 2022 (1666203732)
Build timestamp: 1666203732
Build timestamp as int: 1666203732
```

**Comment by Jaskerv** [comment]
I fixed this resetting my WSL environment. I'm closing this issue as we have no idea what went wrong. Thanks for the help 🎉

**Comment by jacobgardner** [comment]
I ran into this recently on Windows. It was because my `.bazelignore` had windows line endings. By changing the line endings to UNIX line endings, it worked for me.

**Comment by gregmagolan** [comment]
Thanks for the info @jacobgardner. That makes sense given the split on `\n` here: https://github.com/aspect-build/rules_js/blob/main/npm/private/npm_translate_lock_generate.bzl#L461. cc @alexeagle
