### ISSUE TITLE
Recommendation on running Karma?

### ISSUE THREAD

**Issue by gregjacobs** [aspect-build/rules_js#557]
Hey guys, just a quick question. Curious on running Karma: is `@bazel/karma` still the recommendation? Or will there be a `rules_karma` at some point?

**Comment by gregmagolan** [comment]
Great. I'll close this one as answered then. A browser toolchain will come at some point when there is some funding for the project. rules_karma could be a future project as well if there is client who requires it and is willing to fund it.
