### ISSUE TITLE
[Bug]: v1.6.0 breaks popular 3rd party tools like fast-glob

### ISSUE THREAD

**Issue by gregjacobs** [aspect-build/rules_js#577]
### What happened?

After upgrading rules_js to 1.6.0, some of my Node.js scripts immediately started to fail with the following error and no stack trace:

```
TypeError: Cannot assign to read only property 'stackTraceLimit' of function 'function Error() { [native code] }'
```

This took a number of hours to track down (especially due to no stack trace), and I found it's coming from the use of `fast-glob` (https://www.npmjs.com/package/fast-glob), which is a very popular library (38 million+ weekly downloads)

### Version

Development (host) and target OS/architectures: **MacOS Monterey**

Output of `bazel --version`: **5.3.0**

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: **rules_js v1.6.0** (bug was specifically introduced in this version; v1.5.3 is okay)

Language(s) and/or frameworks involved: **Node.js v14.18.1**

### How to reproduce

**BUILD**:

```starlark
js_binary(
    name = "test_fast_glob",
    entry_point = "test-fast-glob.js",
    data = [
        "//:node_modules/fast-glob"
    ]
)
```

**test-fast-glob.js**:

```js
const fastGlob = require('fast-glob');

const files = fastGlob.sync('some-directory/**');
console.log(files);
```

**CLI**: 

```
bazel run //:test_fast_glob
```

### Any other information?

This bug looks to have been specifically introduced by https://github.com/aspect-build/rules_js/pull/546

Couple of things with this:

1. Don't make the global `Error.stackTraceLimit` property unwritable. Can't have 3rd party libraries breaking entire scripts if they want to assign it. We also assign this property on our side when the default Node.js stack trace isn't long enough to track down some of our own errors. 
3. Setting the global `Error.stackTraceLimit` to `0` essentially destroys our ability to debug our Node.js programs. There needs to be a way to opt-out of this functionality (tag on the rule, environment variable, etc.). 
   * Also, any error message that gets raised should tell us how to opt-out of the "set-stack-trace-to-zero" functionality so that developers aren't simply left with a message and no stack trace without knowing that the stack trace has been removed by `rules_js`.

I also question the idea of modifying the global `Error` object at all from within rules_js, but if it increases performance like https://github.com/aspect-build/rules_js/pull/546 says, then at least having the above two points should work around the issues involved with it.

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregjacobs** [comment]
For reference, the overwrite of the global `Error` object is here: https://github.com/jbedard/rules_js/blob/e3e85f92ac9a798f074b83c5898d7dfd82b3cb28/js/private/node-patches/src/fs.ts#L81

Just noticing from the code as well: can this overwrite of the `Error` object happen multiple times? (each time an Error is thrown?) Possibly need a flag to ensure it's only defined once? Or define it on the global error object up front (rather than waiting for an Error to be thrown) so that the functionality is always consistent? 

I'm guessing that some of these libraries try/catch `fs.*Sync` calls, so as soon as one of those errors is thrown, the `Error` object is overwritten and thus would affect the rest of the process.

**Comment by jbedard** [comment]
The fs patches only modify `Error` for the duration of the `fs.*Sync` calls so it shouldn't effect your stack traces in your own code, although maybe we shouldn't hide the primary internal `fs.*Sync` call.

No one (including us) should be assuming `Error.stackTraceLimit` is writable though. Which library is doing that?

**Comment by jbedard** [comment]
@gregjacobs for now we've reverted this since https://github.com/aspect-build/rules_js/commit/78a2405944dfe3eb03c650b4484f1c4d0a3995b7 seems to provide enough of a perf benefits regarding https://github.com/aspect-build/rules_jest/issues/50 (which is what we've been using for this specific performance improvement).

If we try anything like this in the future we'll definitely look back at this and try not to repeat the issues you've raised here.

Thanks for all the time you put into tracking down the root cause of the issue!

**Comment by gregmagolan** [comment]
Should be fixed in https://github.com/aspect-build/rules_js/releases/tag/v1.6.5
