### ISSUE TITLE
[Bug]: Trouble with js_run_devserver and webpack_devserver

### ISSUE THREAD

**Issue by carolosf** [aspect-build/rules_js#599]
### What happened?

I have an example webpack project that I have created here:
https://github.com/carolosf/bazel-rulesjs-webpack-example

By using the autogenerated webpack_cli targets I can build the webpack bundle and run the devserver.
These are implemented with the targets: auto_webpack_build and auto_webpack_dev

However I can't run the example using webpack_devserver from rules_webpack and also can't run it using js_run_devserver from rules_js.
See the targets dev and devserver.

Both error with the following:
```
bazelisk run //:dev
INFO: Analyzed target //:dev (0 packages loaded, 1 target configured).
INFO: Found 1 target...
Target //:dev up-to-date:
  bazel-bin/dev.sh
INFO: Elapsed time: 0.703s, Critical Path: 0.27s
INFO: 4 processes: 4 internal.
INFO: Build completed successfully, 4 total actions
INFO: Build completed successfully, 4 total actions


Starting js_run_devserver //:dev
Syncing...
8 files synced in 9 ms
Running '/private/var/tmp/_bazel_carolosfoscolos/b06cf5e54058faf302829afcac5de380/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/dev.sh.runfiles/webpack/webpack.sh serve --config webpack.config.js' in /var/folders/j0/m8nt5c053mx7k7sw3487nt3w0000gn/T/js_run_devserver-IeDUIc/__main__


node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'import-local'
Require stack:
- /private/var/folders/j0/m8nt5c053mx7k7sw3487nt3w0000gn/T/js_run_devserver-IeDUIc/__main__/node_modules/webpack-cli/bin/cli.js
- /private/var/tmp/_bazel_carolosfoscolos/b06cf5e54058faf302829afcac5de380/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/dev.sh.runfiles/webpack/node_modules/.aspect_rules_js/import-local@3.1.0/node_modules/import-local/index.js
- /private/var/tmp/_bazel_carolosfoscolos/b06cf5e54058faf302829afcac5de380/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/dev.sh.runfiles/webpack/node_modules/.aspect_rules_js/webpack-cli@4.10.0_el2ha5elffcfyvdkz3zzjrzgvy/node_modules/webpack-cli/bin/cli.js
- /private/var/tmp/_bazel_carolosfoscolos/b06cf5e54058faf302829afcac5de380/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/dev.sh.runfiles/webpack/node_modules/.aspect_rules_js/webpack@5.72.1_webpack-cli@4.10.0/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/private/var/folders/j0/m8nt5c053mx7k7sw3487nt3w0000gn/T/js_run_devserver-IeDUIc/__main__/node_modules/webpack-cli/bin/cli.js:5:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/var/folders/j0/m8nt5c053mx7k7sw3487nt3w0000gn/T/js_run_devserver-IeDUIc/__main__/node_modules/webpack-cli/bin/cli.js',
    '/private/var/tmp/_bazel_carolosfoscolos/b06cf5e54058faf302829afcac5de380/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/dev.sh.runfiles/webpack/node_modules/.aspect_rules_js/import-local@3.1.0/node_modules/import-local/index.js',
    '/private/var/tmp/_bazel_carolosfoscolos/b06cf5e54058faf302829afcac5de380/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/dev.sh.runfiles/webpack/node_modules/.aspect_rules_js/webpack-cli@4.10.0_el2ha5elffcfyvdkz3zzjrzgvy/node_modules/webpack-cli/bin/cli.js',
    '/private/var/tmp/_bazel_carolosfoscolos/b06cf5e54058faf302829afcac5de380/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/dev.sh.runfiles/webpack/node_modules/.aspect_rules_js/webpack@5.72.1_webpack-cli@4.10.0/node_modules/webpack/bin/webpack.js'
  ]
}
child tool process exited with code 1
```

### Version

darwin arm64 
bazelisk --version
bazel 5.3.2

Workspace included here https://github.com/carolosf/bazel-rulesjs-webpack-example

### How to reproduce

```shell
Run 
`bazelisk run //:dev` 
or
`bazelisk run //:devserver`
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by alex-torok** [comment]
Copying my comment from https://github.com/aspect-build/rules_webpack/issues/66 since this ticket seems to be more relevant - 

I hit a similar issue on `rules_js@1.6.8` and think the problem is related to the patched fs module enforcing the bazel sandbox. I don't have a reproduction available right now, but followed roughly this path:

* Run my target with `NODE_DEBUG=module`
* See that the failing import is not looking outside of the `/tmp/js_run_devserver-******` directory even though I can see that the files it is looking at are symlinks that should be `realpath`-ed out into the real bazel sandbox. This got me thinking that the issue was the patched fs module.
* Set `patch_node_fs = False` on my tool target and my `js_run_devserver` target (Needed on both)
* Re-run the target with `NODE_DEBUG=module` and see that node is looking outside of the `/tmp/js_run_devserver-******` directory and resolves the module correctly.

Of note: I'm not actually using `rules_webpack` for the target I'm seeing the problem on, but `js_run_devserver` with its tool set to `webpack_dev_server_binary` target from the `webpack-dev-server/package_json.bzl`

**Comment by alex-torok** [comment]
@gregmagolan - friendly ping about this ticket ^

**Comment by gregmagolan** [comment]
Thanks for the ping @alex-torok. We got busy with BazelCon last week so didn't have much time for OSS work. Will take a look at this tomorrow.

**Comment by gregmagolan** [comment]
The problem was very subtle. https://github.com/aspect-build/rules_js/pull/637 will fix it.

**Comment by gregmagolan** [comment]
Confirmed that rules_js @ HEAD solves the issue in the repro https://github.com/carolosf/bazel-rulesjs-webpack-example

```
http_archive(
    name = "aspect_rules_js",
    strip_prefix = "rules_js-8de2fe6556b900c99e2b9dde690f5b8cffdacb19",
    url = "https://github.com/aspect-build/rules_js/archive/8de2fe6556b900c99e2b9dde690f5b8cffdacb19.tar.gz",
)
```

Fix will be included in the next release planned for later today
