### ISSUE TITLE
[Bug]: Does the webpack_cli example support plugins?

### ISSUE THREAD

**Issue by rc-glean** [aspect-build/rules_js#611]
### What happened?

I wonder whether more complicated webpack-cli examples work with plugins. Here's my minimal repro PR https://github.com/rc-glean/rules_js/pull/1 using vanilla CSS' build time css-in-js plugin

1. Add vanilla extract (common build-time css-in-js solution) via https://vanilla-extract.style/documentation/integrations/webpack/

2. `cd examples/webpack_cli`, `pnpm i`

3. `pnpm webpack-cli --config webpack.config.js` Build. Can verify it worked well by observing dist/index.js console logs a generated css class name

4. Observe that `bazel build  //examples/webpack_cli:bundle
` can't find schema-utils ([(plain text gist dump)](https://gist.github.com/rc-glean/e76ae66c0d4a8d9f47f25df40853d9ca), [pretty terminal dump)](https://app.warp.dev/block/n0iy4c9EvCt3IFNpBCKNDP)

Note: I actually got to this issue while trying to debug a different issue from a more complicated monorepo migration
```
Error: Couldn't find parent package.json with a name field from '/private/var/tmp/_bazel_ray/10cd8c3c5e78254de65a5f1a246e1730/sandbox/darwin-sandbox/9978/execroot/privaterepo/bazel-out/darwin-fastbuild/bin'
    at Object.getPackageInfo (/private/var/tmp/_bazel_ray/10cd8c3c5e78254de65a5f1a246e1730/sandbox/darwin-sandbox/9978/execroot/privaterepo/bazel-out/darwin-fastbuild/bin/node_modules/.aspect_rules_js/@vanilla-extract+integration@6.0.0/node_modules/@vanilla-extract/integration/dist/vanilla-extract-integration.cjs.dev.js:300:11)
    at Object.loader (/private/var/tmp/_bazel_ray/10cd8c3c5e78254de65a5f1a246e1730/sandbox/darwin-sandbox/9978/execroot/privaterepo/bazel-out/darwin-fastbuild/bin/node_modules/.aspect_rules_js/@vanilla-extract+webpack-plugin@2.2.0_webpack@5.75.0/node_modules/@vanilla-extract/webpack-plugin/loader/dist/vanilla-extract-webpack-plugin-loader.cjs.dev.js:36:19)
```
We might run into that issue after figuring out the schema-utils issue.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: bazel 5.3.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
I'm using the latest main from rules_js and its examples

Language(s) and/or frameworks involved:
vanilla CSS

### How to reproduce

```shell
1. Add vanilla extract (common build-time css-in-js solution) via https://vanilla-extract.style/documentation/integrations/webpack/

2. `cd examples/webpack_cli`, `pnpm i`

3. `pnpm webpack-cli --config webpack.config.js` Build. Can verify it worked well by observing dist/index.js console logs a generated css class name

4. Observe that `bazel build  //examples/webpack_cli:bundle
` can't find schema-utils ([(plain text gist dump)](https://gist.github.com/rc-glean/e76ae66c0d4a8d9f47f25df40853d9ca), [pretty terminal dump)](https://app.warp.dev/block/n0iy4c9EvCt3IFNpBCKNDP)
```

### Any other information?

See how to reproduce

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
The crux of the problem of your minimal repro is that you're passing the `:node_modules` npm dependencies through a `filegroup` target which drops the JsInfo provider and only forwards the DefaultInfo from each target which doesn't contain the completely virtual store.

Just switching the `filegroup` to `js_library` in the repro is enough to get it to build.

**Comment by gregmagolan** [comment]
I put up a PR https://github.com/aspect-build/rules_js/pull/640 that includes the plugins in your repro wired up through a js_library
