### ISSUE TITLE
Support bzlmod in rules_js family of repos

### ISSUE THREAD

**Issue by kormide** [aspect-build/rules_js#63]
Tracking issue:

- [x] rules_js
- [x] rules_ts
- [x] rules_swc
- [x] rules_esbuild
- [x] rules_terser
- [ ] rules_webpack
- [ ] rules_rollup
- [x] rules_jest https://github.com/aspect-build/rules_jest/issues/79
- [x] rules_jasmine
- [ ] rules_cypress

**Comment by kormide** [comment]
Yep I can take that for my 20%.

**Comment by alexeagle** [comment]
rollup is in https://github.com/aspect-build/rules_rollup/pull/72

**Comment by alexeagle** [comment]
I think we've done as many of these as we plan to currently. Can use issues on those repos for any follow-up work.
