### ISSUE TITLE
[FR]: Coarse node_modules dependencies

### ISSUE THREAD

**Issue by sashamor** [aspect-build/rules_js#634]
### What is the current behavior?

Unsure. Does aspect's rules_js already support depending on all node_modules in the package.json?

Adding "@npm//:node_modules" as a dependency just adds an empty folder (likely because the dependencies are lazy-loaded).

### Describe the feature

The old rules_js rules supported coarse node_modules dependencies:
https://bazelbuild.github.io/rules_nodejs/dependencies.html#coarse-node_modules-dependencies

E.g.:
```bazel
load("@build_bazel_rules_nodejs//:index.bzl", "nodejs_binary")

nodejs_binary(
    name = "bar",
    node_modules = "@npm//:node_modules",
)
```

to include all node_modules listed in the `npm` package.json. Is there an equivalent for the new aspect rules?

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
Yes. You can depend on the `//:node_modules` coarse target as the equivalent.

**Comment by sashamor** [comment]
Ahh - I found some bugs in my own code where I'm relying on transient dependencies, which this new aspect rules (correctly) doesn't allow you to do, so it looked like the packages weren't there, but they just weren't explicitly listed as dependencies. Thanks!

**Comment by gregmagolan** [comment]
No problem. If you run into undeclared dependencies in npm packages that you depend on you can inject them into the pnpm lock file with [pnpm.packageExtensions](https://pnpm.io/package_json#pnpmpackageextensions). For example, https://github.com/aspect-build/rules_js/blob/fb1f84aca12627308422097e433fb2eb52b0cf23/package.json#L9
