### ISSUE TITLE
[FR]: Document how to bootstrap a pnpm lock file

### ISSUE THREAD

**Issue by philsc** [aspect-build/rules_js#649]
### What is the current behavior?

The docs currently have [this](https://github.com/aspect-build/rules_js/blob/main/docs/faq.md#can-i-use-bazel-managed-pnpm) to say about invoking `pnpm`:
> just run `bazel run -- @pnpm//:pnpm --dir $PWD` followed by the usual arguments to pnpm.

I wanted to use that invocation to create a lock file from our `package.json` file.

However, as far as I can tell, that only works once you have an `npm_translate_lock()` call in your WORKSPACE file. That call, in turn, requires a pnpm lock file.

After some trial and error, here are the steps I went through to create a pnpm lock file.

1. Create a `npm_translate_lock()` call in the workspace pointing at an empty `pnpm-lock.yaml`.
2. Put the following contents in the `pnpm-lock.yaml` file:

        lockfileVersion: 5.4
        packages: {}
3. Patch `rules_js` with the following:

        --- a/npm/private/npm_translate_lock.bzl
        +++ b/npm/private/npm_translate_lock.bzl
        @@ -236,8 +236,8 @@ def _gen_npm_imports(lockfile, root_package, attr, registries, default_registry)
                 fail("prod and dev attributes cannot both be set to true")

             packages = lockfile.get("packages")
        -    if not packages:
        -        fail("expected packages in processed lockfile")
        +    #if not packages:
        +    #    fail("expected packages in processed lockfile")

             importers = lockfile.get("importers")
             if not importers:
        @@ -620,8 +620,8 @@ def _impl(rctx):
             ]

             packages = lockfile.get("packages")
        -    if not packages:
        -        fail("expected packages in processed lockfile")
        +    #if not packages:
        +    #    fail("expected packages in processed lockfile")

             importers = lockfile.get("importers")
             if not importers:
4. Then run `bazel run -- @pnpm//:pnpm --dir $PWD install --lockfile-only`.

That gives me a functional lock file as far as I can tell.

### Describe the feature

I would like to offer to document this bootstrapping process. Alternatively I'll document a better one if folks have one.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by alexeagle** [comment]
Yeah, good observation. I think most users just install pnpm with `npm install -g` so they don't really care to use the exact version that Bazel has.

At the top level, `npm_translate_lock` is a wrapper macro that has the convenience of creating the `@pnpm` repo: https://github.com/aspect-build/rules_js/blob/main/npm/npm_import.bzl#L345-L355
so I think the ideal workflow for you would be to setup WORKSPACE to the point of having rules_js present, call a new repository rule like `pnpm_dependencies()` and then you can run the `pnpm` command before you have a lockfile.

**Comment by alexeagle** [comment]
@philsc keep the awesome feedback coming please :)
Let me know if we can do more for your org.

**Comment by philsc** [comment]
Definitely! Thank you for all this. rules_js is proving a major success at Aurora.

Though this particular feature request came out of trying to migrate our [FRC robotics code base](https://github.com/frc971/971-Robot-Code) away from rules_nodejs.
