### ISSUE TITLE
[FR]: Make `@pnpm//:pnpm` public

### ISSUE THREAD

**Issue by jfirebaugh** [aspect-build/rules_js#657]
### What is the current behavior?

rules_js generates a BUILD file for the `@pnpm` repository containing a `js_binary` rule for running pnpm:

https://github.com/aspect-build/rules_js/blob/b40680d50a74a891fad1dd6ceb594c17e7164133/npm/npm_import.bzl#L59

This rule can be used via `bazel run @pnpm//:pnpm`, but because it has default (private) visibility, it can't be used in build targets (say as the `tool` of a `js_run_binary` rule).

### Describe the feature

Add `visibility = ["//visibility:public"]` to the generated `@pnpm//:pnpm` rule.

The motivation for me is to support the following macro:

```
def pnpm_import():
    js_run_binary(
        name = "pnpm_import",
        args = ["import"],
        tool = "@pnpm//:pnpm",
        chdir = native.package_name(),
        srcs = [
            "package.json",
            "package-lock.json",
        ],
        outs = [
            "pnpm-lock.yaml",
        ],
    )
    write_source_files(
        name = "update_pnpm_lock",
        files = {
            "pnpm-lock.yaml": "pnpm-lock.yaml",
        },
        suggested_update_target = "//bazel/js/repositories:update",
        visibility = ["//bazel/js/repositories:__pkg__"],
    )
```

This will allow me to replace `npm_translate_lock(..., npm_package_lock = ...)` with `npm_translate_lock(..., pnpm_lock = ...)`. I want to preserve `npm` as the user-facing package manager for developers at Figma, but have a checked-in `pnpm-lock.yml` so that builds are fast (running `pnpm import` at build time is slow).

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by alexeagle** [comment]
It makes sense for that to be public, yes - BUT @gregmagolan has a nicer formulation for this "keep my pnpm-lock.yaml up-to-date" problem cooking: https://github.com/aspect-build/rules_js/pull/650

You'll probably want that instead.
