### ISSUE TITLE
[FR]: Is out_dirs and output_dir for webpack_cli supported?

### ISSUE THREAD

**Issue by rc-glean** [aspect-build/rules_js#662]
### What is the current behavior?

Minimal repro (but unsure if user error): https://github.com/aspect-build/rules_js/pull/661/files

Using rules_nodejs + yarn_install, typically, we can build all bundles for webpack.config.js via `output_dir = True`

I see that the equivalent rules_js bin.webpack_cli has an output_dir option, but it seems to not emit any bundles.

```
# note: rules_nodejs yarn_install'd output_dir = True is sufficient for outputting
#
# `bazel build //examples/webpack_cli:bundle_dir`
bin.webpack_cli(
    name = "bundle_dir",
    srcs = [
        "webpack.config.js",
        ":lib",
    ],

    # Emits an `ls bazel-bin/examples/webpack_cli/bundle_dir`, but contents empty
    output_dir = True,

    # Emits an `ls bazel-bin/examples/webpack_cli/raytest`, but contents empty
    out_dirs = ["raytest"],
    args = [
        "--config webpack.config.js",
    ],
    chdir = package_name(),
    log_level = "debug",
)
```

### Describe the feature

If my minimal repro isn't user error, should there be parity between webpack_cli in rules_js and rules_nodejs?

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
The issue here was a mismatch between the output directory configured in the BUILD file and the output directory configured in the webpack config in the minimal repro.

See https://github.com/aspect-build/rules_js/pull/661#issuecomment-1341910713 and https://github.com/aspect-build/rules_js/pull/661#issuecomment-1381422371
