### ISSUE TITLE
node-fs patches performance

### ISSUE THREAD

**Issue by jbedard** [aspect-build/rules_js#668]
`@rollup/plugin-node-resolve` example: https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1669826690326189

Jest example: https://github.com/aspect-build/rules_jest/issues/50

Potential changes:
* ✅ add caching to async path: https://github.com/aspect-build/rules_js/pull/1007

**Comment by gregmagolan** [comment]
@jbedard landed a number of performance improvements to fs-patches but there are still more to come so keeping this open and setting status to "In Progress" in the new Aspect Open Source project

**Comment by gregmagolan** [comment]
We measured improvements showing that rules_js is as fast or faster than patches in rules_nodes for executing large test targets. We also heard from users on Bazel Slack that the performance improvements landed have significantly improved their build & test times. For examples, https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1682349811639969?thread_ts=1669826690.326189&cid=CEZUUKQ6P
