### ISSUE TITLE
[Bug]: Transitive dependencies are not present in `js_image_layer`'s node_modules

### ISSUE THREAD

**Issue by flolu** [aspect-build/rules_js#677]
### What happened?

I'm using [js_image_layer](https://github.com/aspect-build/rules_js/blob/9652d5d484cca26c9993cfee5443727ff71bebe2/e2e/js_image/js_image_layer.bzl) to build Docker images. But currently, transitive dependencies of node_modules are not passed on to it.

### Version

Development (host) and target OS/architectures: Linux (Fedora)

Output of `bazel --version`:
```
Bazelisk version: v1.13.2
Build label: 7.0.0-pre.20221102.3
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Nov 11 18:06:13 2022 (1668189973)
Build timestamp: 1668189973
Build timestamp as int: 1668189973
```

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

- rules_js-1.8.0
- rules_ts-1.0.2
- rules_swc-0.19.3
- rules_pkg-0.8.0
- rules_docker-0.25.0

### How to reproduce

```shell
git clone https://github.com/flolu/rules-ts-transitive-deps
cd rules-ts-transitive-deps
pnpm i
bazelisk run //:image && docker run --rm -it bazel:image
```

**Comment by flolu** [comment]
@thesayyn do you know how to prevent having to specify transitive dpendencies?

**Comment by thesayyn** [comment]
they should be included automatically. Is this happening with all packages or single one?

**Comment by flolu** [comment]
@thesayyn it's happening with all packages. you can check the repro: https://github.com/flolu/rules-ts-transitive-deps

**Comment by matthewjh** [comment]
I am also seeing this issue, but only with certain transitive deps.

**Comment by flolu** [comment]
@thesayyn any updates?

**Comment by matthewjh** [comment]
> 

Update: my issue turned out to be caused by something else. There was some difference between my local pnpm-installed node_modules and the rules_js-managed ones (perhaps because I didn't set `hoist=false` in my `.npmrc`?) that generated a difference in runtime module resolution between my local `bazel run` and running the built binary inside the docker image. Modules should not be resolved out of the runfiles, anyway, but that is slightly broken due to #656 and #362.

However, I have separately noticed `ts_project` deps not being propagated in an _all or nothing_ way in sandboxed build actions, so I still think this issue is valid.

**Comment by flolu** [comment]
@mvukov I've tried to patch my repro from this issue with the fix from your [pull request](https://github.com/aspect-build/rules_ts/pull/280) on this [branch](https://github.com/flolu/rules-ts-transitive-deps/tree/fix-mvukov).

But the issue still persists. Did I mess up the patching?

**Comment by thesayyn** [comment]
> However, I have separately noticed `ts_project` deps not being propagated in an _all or nothing_ way in sandboxed build actions, so I still think this issue is valid.

i can confirm that the cause of this issue is indeed ts_project. 

@flolu yes that's the solution to this particular problem. 

for what is worth, you may workaround this problem by listing your deps in npm_package. until

```diff
diff --git a/BUILD.bazel b/BUILD.bazel
index 9c37fed..936f4c0 100644
--- a/BUILD.bazel
+++ b/BUILD.bazel
@@ -2,12 +2,11 @@ load("@npm//:defs.bzl", "npm_link_all_packages")
 load("@aspect_rules_ts//ts:defs.bzl", "ts_config", "ts_project")
 load("@aspect_bazel_lib//lib:copy_to_bin.bzl", "copy_to_bin")
 load("@aspect_rules_swc//swc:defs.bzl", "swc")
-load("@aspect_rules_js//js:defs.bzl", "js_binary")
+load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_image_layer")
 load("@aspect_rules_js//npm:defs.bzl", "npm_link_package")
 load("@bazel_skylib//lib:partial.bzl", "partial")
 load("@io_bazel_rules_docker//container:container.bzl", "container_image")
 load("@io_bazel_rules_docker//container:layer.bzl", "container_layer")
-load("//:js_image_layer.bzl", "js_image_layer")
 
 package(default_visibility = ["//visibility:public"])
 
@@ -66,20 +65,32 @@ js_image_layer(
     root = "/app",
 )
 
+filegroup(
+    name = "app_tar",
+    srcs = [":layers"],
+    output_group = "app",
+)
+
 container_layer(
     name = "app_layer",
-    tars = [":layers/app.tar"],
+    tars = [":app_tar"],
+)
+
+filegroup(
+    name = "node_modules_tar",
+    srcs = [":layers"],
+    output_group = "node_modules",
 )
 
 container_layer(
     name = "node_modules_layer",
-    tars = [":layers/node_modules.tar"],
+    tars = [":node_modules_tar"],
 )
 
 container_image(
     name = "image",
-    architecture = "amd64",
-    base = "@debian_amd64//image",
+    architecture = "arm64",
+    base = "@debian_arm64//image",
     cmd = ["/app/bin.sh"],
     entrypoint = ["bash"],
     layers = [

```

**Comment by flolu** [comment]
@thesayyn the patch you provided doesn't seem to work for me:
```
ERROR: /home/flolu/Desktop/rules-ts-transitive-deps/BUILD.bazel:86:16: in tars attribute of container_layer_ rule //:node_modules_layer: '//:node_modules_tar' does not produce any container_layer_ tars files (expected .tar, .tar.xz, .tar.gz or .tgz). Since this rule was created by the macro 'container_layer', the error might have been caused by the macro implementation
ERROR: /home/flolu/Desktop/rules-ts-transitive-deps/BUILD.bazel:86:16: Analysis of target '//:node_modules_layer' failed
ERROR: Analysis of target '//:image' failed; build aborted
```

**Comment by thesayyn** [comment]
> the patch you provided doesn't seem to work for me:

sorry. updated it.

**Comment by flolu** [comment]
@thesayyn thanks, now the workaround works.

**Comment by flolu** [comment]
@thesayyn do you have any idea why [this branch](https://github.com/flolu/rules-ts-transitive-deps/tree/fix-mvukov) doesn't work even though I've [patched](https://github.com/flolu/rules-ts-transitive-deps/blob/63e9213eaed012a61f31ca7cb98ea712908ce6ae/WORKSPACE#L44) `ts_project`?

**Comment by gregmagolan** [comment]
Marking this one as a dup of https://github.com/aspect-build/rules_ts/issues/268. Similar pattern to https://github.com/aspect-build/rules_jest/issues/72 with a ts_project being depended on via a linked npm_package. In this case the targets are:
```
ts_project(
    name = "lib2_project",
    srcs = ["index.ts"],
    composite = True,
    declaration = True,
    transpiler = partial.make(
        swc,
        swcrc = "//:swcrc",
    ),
    tsconfig = "//:tsconfig",
    deps = ["//:node_modules/@faker-js/faker"],
)

npm_package(
    name = "lib2",
    srcs = [":lib2_project"],
    package = "@org/lib2",
    visibility = ["//visibility:public"],
)
```
