### ISSUE TITLE
[Bug]:  Copying files to directory failed: Exec failed due to IOException: null

### ISSUE THREAD

**Issue by matthewjh** [aspect-build/rules_js#685]
### What happened?

I sporadically see this on our CI builds, which use local exec as well as remote caching:

```
Copying files to directory failed: Exec failed due to IOException: null
```

Seems like a race condition.

Our project is a collection of `ts_project`, `js_library`, `npm_package`, etc. all the standard pieces.

There is no other information (errors, stack traces, etc) there to give you.

Does anyone else see this?

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

6.0.0rc4

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

```python
http_archive(
        name = "aspect_rules_js",
        sha256 = "d8feeb67bca55cc56fb4696cf6c852f4a44c0c8dbe99ea108f6a95fd322b4bcb",
        strip_prefix = "rules_js-1.7.0",
        url = "https://github.com/aspect-build/rules_js/archive/refs/tags/v1.7.0.tar.gz",
        patches = [
            "//tools/bazel-patches:rules_js.patch",
        ],
        patch_args = ["-p1"],
    )

    http_archive(
        name = "aspect_rules_ts",
        sha256 = "555f408bf664e553eb148f22dc2da9e82177413bd08d2d19180340962cf3ff86",
        strip_prefix = "rules_ts-1.0.0-rc7",
        url = "https://github.com/aspect-build/rules_ts/archive/refs/tags/v1.0.0-rc7.tar.gz",
    )

    http_archive(
        name = "aspect_rules_esbuild",
        sha256 = "d64d6753defbc99f6de06a1060b04c5f0b17fcddde9748541564663e5b407022",
        strip_prefix = "rules_esbuild-0.13.3",
        url = "https://github.com/aspect-build/rules_esbuild/archive/refs/tags/v0.13.3.tar.gz",
    )

    http_archive(
        name = "aspect_rules_jasmine",
        sha256 = "938a2818100fd89e7600a45b7ba4fcd4114c11c5b5741db30ff7c6e0dcb2ea4b",
        strip_prefix = "rules_jasmine-0.1.0",
        url = "https://github.com/aspect-build/rules_jasmine/archive/refs/tags/v0.1.0.tar.gz",
    )

    http_archive(
        name = "aspect_rules_webpack",
        sha256 = "ec88e0c330661ed935534229c5e8480cb7ab281da4eca1b9b0b133374a724e66",
        strip_prefix = "rules_webpack-0.4.0",
        url = "https://github.com/aspect-build/rules_webpack/archive/refs/tags/v0.4.0.tar.gz",
    )

http_archive(
        name = "aspect_bazel_lib",
        sha256 = "695d319362b227725e4daa60d863b4d1969b167889902511f1fd3051cea1071f",
        strip_prefix = "bazel-lib-1.16.3",
        url = "https://github.com/aspect-build/bazel-lib/archive/refs/tags/v1.16.3.tar.gz",
    )

```

Language(s) and/or frameworks involved:

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
Not much to go on here. Can you tell which target is creating the error?

**Comment by gregmagolan** [comment]
`copy_to_directory` impl has been completely re-written to use a pre-built golang binary to perform the copies for improved performance. This issue is very likely no longer reproducible in the reported form so I'm going to close it. Please re-open or open a new issue if it is seen again.

**Comment by matthewjh** [comment]
@gregmagolan I am still seeing this issue. An extra piece of information I can now give is that I can repro this with `remote_download_toplevel` but not without it.
