### ISSUE TITLE
Question: How to run commands defined in `scripts` in `package.json`

### ISSUE THREAD

**Issue by imWildCat** [aspect-build/rules_js#705]
Hello, sorry if I chose the wrong place to ask questions.
I read most of the documents but cannot find how to simply run the `build` script defined below.

I was trying to integrate Bazel for the frontend stack of a Rails app.

```json
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "^3.1.1",
    "@hotwired/turbo-rails": "^7.2.4",
    "autoprefixer": "^10.4.13",
    "esbuild": "^0.15.12",
    "postcss": "^8.4.18",
    "tailwindcss": "^3.2.1"
  },
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=assets",
    "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --minify"
  }
}
```

**Comment by gregmagolan** [comment]
The build steps in scripts need to be translated into Bazel BUILD targets. On migrations, we will often keep the "scripts" around that developers can keep running the local workflows they are used to but the scripts call bazel to build artifacts or to run tests. For example this [create-react-scripts app build with bazel](https://github.com/aspect-build/bazel-examples/blob/ec19825e711ef2d1db68352ed8b152cad65cd257/react-cra/package.json#L24).

We have [rule set for esbuild](https://github.com/aspect-build/rules_esbuild). It hasn't reach maturity with a 1.0.0 release but we are committed to maintaining that one. We use it internally ourselves.

tailwindcss you could probably run with the auto-generated bin rules similar to how webpack is run in this [example](https://github.com/aspect-build/rules_js/blob/f02a68c2e9d4e38ee15ff1535bfafc3d2d1b9a16/examples/webpack_cli/BUILD.bazel#L25.
).

We offer Bazel training and consulting as well if you wanted more direct help.

**Comment by imWildCat** [comment]
Understand, thank you very much!

**Comment by gregmagolan** [comment]
Bazel Slack #javascript channel is a good place to ask question as well. There is a very active community there. https://slack.bazel.build/
