### ISSUE TITLE
[FR]: Support patches with `a/node_modules/pkg` paths

### ISSUE THREAD

**Issue by gregmagolan** [aspect-build/rules_js#711]
Existing non-bazel code bases may have a slew of npm patches generated with `patch-package` that have diff paths `a/node_modules/foo/src/file.js b/node_modules/foo/src/file.js`. rules_js npm_translate_lock expects patches to have paths relative to root of the package instead `a/src/file.js b/src/file.js`. To make migrations easier and to make it easier to run both `pnpm install` that uses `patch-package` outside of bazel and the bazel build, rules_js should support patches with `a/node_modules/foo/src/files.js` paths.

**Comment by gregmagolan-codaio** [comment]
@alexeagle pointed out that this is already supported in rules_js using either `-p3` or `-p4` patch args.

For example,

```
    patch_args = {
        # Use `-p3` or `-p4` (short for `--strip=3` and `--strip=4`) to strip `a/node_modules/foo` and `a/node_modules/@fum/bar` off of the
        # diff paths in patch files generated by `patch-package`. See https://man7.org/linux/man-pages/man1/patch.1.html for more info.
        "@fum/bar@0.0.1": ["-p4"],
        "foo@1.2.3": ["-p3"],
    },
    patches = {
        "@fum/bar@18.0.10": ["//:patches/@fum+bar+0.0.1.patch"],
        "foo@1.2.3": ["//:patches/foo+1.2.3.patch"],
    },
```

We should add this to the new pnpm docs as well

**Comment by gregmagolan** [comment]
@alexeagle pointed out that this is already supported in rules_js using either `-p3` or `-p4` patch args.

For example,

```
    patch_args = {
        # Use `-p3` or `-p4` (short for `--strip=3` and `--strip=4`) to strip `a/node_modules/foo` and `a/node_modules/@fum/bar` off of the
        # diff paths in patch files generated by `patch-package`. See https://man7.org/linux/man-pages/man1/patch.1.html for more info.
        "@fum/bar@0.0.1": ["-p4"],
        "foo@1.2.3": ["-p3"],
    },
    patches = {
        "@fum/bar@18.0.10": ["//:patches/@fum+bar+0.0.1.patch"],
        "foo@1.2.3": ["//:patches/foo+1.2.3.patch"],
    },
```

We should add this to the new pnpm docs as well
