### ISSUE TITLE
[Bug]: Unable to run `npm_import`-ed binaries when using `rules_js` with bzlmod

### ISSUE THREAD

**Issue by ztl8702** [aspect-build/rules_js#745]
### What happened?

```
ERROR: Skipping ':build': error loading package '': at /home/node/.cache/bazel/_bazel_node/bd31105343571d27cb38c68d58484397/external/aspect_rules_js~1.13.0~npm~npm/vite/package_json.bzl:1:6: Unable to find package for @[unknown repo 'aspect_rules_js~1.13.0~npm~npm__vite__4.0.3' requested from @aspect_rules_js~1.13.0~npm~npm]//:package_json.bzl: The repository '@[unknown repo 'aspect_rules_js~1.13.0~npm~npm__vite__4.0.3' requested from @aspect_rules_js~1.13.0~npm~npm]' could not be resolved: No repository visible as '@aspect_rules_js~1.13.0~npm~npm__vite__4.0.3' from repository '@aspect_rules_js~1.13.0~npm~npm'.
```

I am trying to run `vite`, in a similar fashion as https://github.com/aspect-build/bazel-examples/blob/ec19825e711ef2d1db68352ed8b152cad65cd257/vue/BUILD.bazel#L31-L36, but with bzlmod.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

bazel 6.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
```
# MODULE.bazel
bazel_dep(name = "aspect_rules_js", version = "1.13.0")

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
npm.npm_translate_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)
use_repo(npm, "npm")
use_repo(npm, "pnpm")
```

Language(s) and/or frameworks involved:

### How to reproduce

Minimum repro example: https://github.com/ztl8702/bazel-rule-js-repro/tree/e65fd574a3d1a7faea8184672222be7680b244da

BUILD file: https://github.com/ztl8702/bazel-rule-js-repro/blob/e65fd574a3d1a7faea8184672222be7680b244da/BUILD.bazel

1.
   ```shell
   git clone https://github.com/ztl8702/bazel-rule-js-repro
   cd bazel-rule-js-repro
   git checkout e65fd574a3d1a7faea8184672222be7680b244da
   ```

1. Run **without** bzlmod
   ```
   bazel run :build
   ```

1. Run with bzlmod
   ```
   bazel run --config=bzlmod :build
   ```

**Expected:** Both runs succeed

**Actual:**  when using bzlmod, it fails when the "repository could not be resolved" error above

### Fund our work

- [x] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/) CONTRIBUTION #609797

**Comment by ztl8702** [comment]
Is this related to #644? I am quite new to bzlmod. Would love more insights into how to debug issues like this.

**Comment by ztl8702** [comment]
If I change the `load` statement in my BUILD file to [canonical repository name](https://bazel.build/build/bzlmod#repository-names:~:text=two%20important%20concepts%3A-,Canonical%20repository%20name,-%3A%20The%20globally%20unique):

```diff
--- a/BUILD.bazel
+++ b/BUILD.bazel
@@ -1,5 +1,5 @@
 load("@npm//:defs.bzl", "npm_link_all_packages")
-load("@npm//:vite/package_json.bzl", vite_bin = "bin")
+load("@@aspect_rules_js~1.13.0~npm~npm__vite__4.0.3//:package_json.bzl", vite_bin = "bin")
```

it works.

So now the question is: what would be the "apparent repository name" for `aspect_rules_js~1.13.0~npm~npm__vite__4.0.3`? Why doesn't `@npm` repository contain `vite`?

**Comment by ztl8702** [comment]
This [Slack thread](https://bazelbuild.slack.com/archives/C03MSRTSTUL/p1666369301118539) looks related.

**Comment by alexeagle** [comment]
thanks for the donation!

**Comment by ztl8702** [comment]
Thanks for the rapid fix 🤛
