### ISSUE TITLE
[Bug]: Using binaries from npm not working as expected

### ISSUE THREAD

**Issue by kreempuff** [aspect-build/rules_js#769]
### What happened?

I'm trying to use the [remotion cli](https://www.remotion.dev/) as [documented](https://github.com/aspect-build/rules_js/tree/d0e08695e50b868346835d8023f5557acd0c77bb/docs#using-binaries-published-to-npm) with this load statement:  `load("@video_production_playground_npm//:@remotion/cli/package_json.bzl", remotion_bin = "bin")` but I get an error:
```
ERROR: error loading package 'video-production/playground': cannot load '@video_production_playground_npm//:@remotion/cli/package_json.bzl': no such file
INFO: Elapsed time: 0.531s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded)
FAILED: Build did NOT complete successfully (5 packages loaded)
currently loading: video-production/playground ... (2 packages)
```

It also fails when I try to replicate the typescript example. It feels like I'm missing something small but critical. 

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:
`bazel 5.4.0`

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
```
## Nodejs dependencies
http_archive(
    name = "aspect_rules_js",
    sha256 = "686d5b345592c1958b4aea24049d935ada11b83ae5538658d22b84b353cfbb1e",
    strip_prefix = "rules_js-1.13.1",
    url = "https://github.com/aspect-build/rules_js/archive/refs/tags/v1.13.1.tar.gz",
)


load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")
rules_js_dependencies()

load("@rules_nodejs//nodejs:repositories.bzl", "DEFAULT_NODE_VERSION", "nodejs_register_toolchains")
nodejs_register_toolchains(
    name = "nodejs",
    node_version = DEFAULT_NODE_VERSION,
)

load("@aspect_rules_js//npm:npm_import.bzl", "npm_translate_lock")

npm_translate_lock(
    name = "video_production_playground_npm",
    pnpm_lock = "//video-production/playground:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)

load("@video_production_playground_npm//:repositories.bzl", "npm_repositories")
npm_repositories()

## END Nodejs dependencies
```
Language(s) and/or frameworks involved:

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by ztl8702** [comment]
try `@video_production_playground_npm//video-production/playground:@remotion/cli/package_json.bzl`

**Comment by gregmagolan** [comment]
`@video_production_playground_npm//video-production/playground:@remotion/cli/package_json.bzl` should work in this case

The Bazel package (`video-production/playground`) where the npm package you're loading the `package_json.bzl` from is linked to is part of the load path since the same package may be linked to different locations in your WORKSPACE.

**Comment by kreempuff** [comment]
@gregmagolan @ztl8702 That worked! I guess I don't fully understand the linking that's going on and how it relates to the external repo structure generated by these rules
