### ISSUE TITLE
[FR]: Improve error message when npm_repositories() is forgotten in WORKSPACE

### ISSUE THREAD

**Issue by gonzojive** [aspect-build/rules_js#770]
### What is the current behavior?

Error message like

```
$ bazel build //:node_modules
ERROR: Skipping '//:node_modules': error loading package '': at /home/red/.cache/bazel/_bazel_red/9f975204b5973dd8a05172c6f645e273/external/example_npm/defs.bzl:5:6: Unable to find package for @example_npm__google-protobuf__3.21.2__links//:defs.bzl: The repository '@example_npm__google-protobuf__3.21.2__links' could not be resolved: Repository '@example_npm__google-protobuf__3.21.2__links' is not defined.
WARNING: Target pattern parsing failed.
ERROR: error loading package '': at /home/red/.cache/bazel/_bazel_red/9f975204b5973dd8a05172c6f645e273/external/example_npm/defs.bzl:5:6: Unable to find package for @example_npm__google-protobuf__3.21.2__links//:defs.bzl: The repository '@example_npm__google-protobuf__3.21.2__links' could not be resolved: Repository '@example_npm__google-protobuf__3.21.2__links' is not defined.
INFO: Elapsed time: 0.258s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: 
```

### Describe the feature

Print a better error message if an expected repository doesn't exist that suggests a common fix.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
Unfortunately this error message is controlled by Bazel itself and I don't know of anyway of to improve it in rules_js. Augmenting bad Bazel error messages is possible with the Aspect CLI [plugin-augment-error](https://docs.aspect.build/plugins/aspect-build/plugin-augment-error/). The principled solution, however, is to upgrade to [bzlmod](https://github.com/aspect-build/bazel-examples/blob/main/bzlmod/MODULE.bazel) with Bazel 6 which eliminates many problems like this which come with using WORKSPACE files. 

Not all rule sets work with bzlmod yet as it is very new and there are still a few features of `npm_translate_lock` that we're [working on](https://github.com/aspect-build/rules_js/pull/767) but we're planning to have all of our rule sets be bzlmod compatible.
