### ISSUE TITLE
[FR]: Support dependency from local tgz

### ISSUE THREAD

**Issue by tanishiking** [aspect-build/rules_js#792]
### What is the current behavior?

Originally reported in [bazel slack](https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1673622123840789?thread_ts=1673580672.796649&cid=CEZUUKQ6P)
Reproducible example: https://github.com/tanishiking/bazel-playground/tree/main/15-rules-cra-dir

When we have a dependency on local tgz.

For example,
```
"lodash": "file:public/lodash-4.17.21.tgz",
```

Passing tgz to `npm_translate_lock` via the `data` attribute.

```python
npm_translate_lock(
    name = "npm",
    # npm_package_lock = "//:package-lock.json",
    npmrc = "//:.npmrc",
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
    data = [
        "//:package.json",
        "//public:lodash-4.17.21.tgz"
    ],
)
```

And run `bazel build //...` we get, (for example) the following error

```
ERROR: /Users/tanishiking/src/github.com/tanishiking/bazel-playground/15-rules-cra-dir/app/BUILD.bazel:3:22: no such package 'app/public/lodash-4.17.21.tgz': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/tanishiking/src/github.com/tanishiking/bazel-playground/15-rules-cra-dir/app/public/lodash-4.17.21.tgz and referenced by '//app:.aspect_rules_js/node_modules/lodash@0.0.0'
ERROR: Analysis of target '//app:cra' failed; build aborted:
```

### Describe the feature

As `rules_nodejs` can refer to local tgz, rules_js should be able to install dependency from tgz.

---

The workaround is:

> In the meantime, you can extract the tgz and check-in the result and just point your package.json to the extracted directory. You'll need add a BUILD file and a default npm_package target in the extracted directory for the linker to use. For example, https://github.com/aspect-build/rules_js/blob/ce65b00b5482cec3eb73e56c5b89fd0c044277e3/npm/private/test/vendored/is-odd/BUILD.bazel#L3
> If your npm_translate_lock is referencing the pnpm lock file then you don't need any data attribute in npm_translate_lock. That is only needed when you're using a yarn or npm lock file as the source-of-truth. 
> https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1673628248779719?thread_ts=1673580672.796649&cid=CEZUUKQ6P

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
This looks great. I'll have to land a prefactor so that npm_translate_lock can copy over binary files from `data` so that this feature will be compatible with `update_pnpm_lock = True`.
