### ISSUE TITLE
[FR]: Add renamed symbols to the release snippets

### ISSUE THREAD

**Issue by paullewis** [aspect-build/rules_js#817]
### What is the current behavior?

Today when you import any of the Aspect rules they usually have a `LATEST_VERSION` value:

```bazel
load("@aspect_rules_ts//ts:repositories.bzl", "rules_ts_dependencies", "LATEST_VERSION")
```

### Describe the feature

Super minor, but when you have multiple rules on the go you end up renaming `LATEST_VERSION` to something like `TS_LATEST_VERSION` in the `WORKSPACE` to avoid clashes with other `LATEST_VERSION`s, i.e., 

```bazel
load("@aspect_rules_ts//ts:repositories.bzl", "rules_ts_dependencies", TS_LATEST_VERSION = "LATEST_VERSION")
```

I wondered whether it would be worth either updating the snippet that folks copy-paste, or renaming `LATEST_VERSION` to be rules-specific.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
Thanks for the suggestion @paullewis. I think its a good idea to reduce friction.
