### ISSUE TITLE
[Bug]: .npmrc registry is not sanitized

### ISSUE THREAD

**Issue by Aghassi** [aspect-build/rules_js#822]
### What happened?

If your `.npmrc` has the following

```
registry = 'https://url.com'
```

this rule will take `'` and not remove the strings. This will cause installs to fail.

### Version

Development (host) and target OS/architectures: Ventura 13.2

Output of `bazel --version`: 6.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### How to reproduce

```shell
add a registry to .npmrc that is equal to a string
```

### Any other information?

Maybe surface a validation message. Took me a while to find this. Had to `bazel fetch` the target to find the failure

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by Aghassi** [comment]
Example of the error log

```
 Bad URL: 'https://url.com/'/ansi-regex/-/ansi-regex-5.0.1.tgz
```

**Comment by gregmagolan** [comment]
@jbedard Did you recently make a similar change to be tolerant of double quotes `"`?

**Comment by jbedard** [comment]
Yeah, I guess this is the exact same but single quotes... 👍
