### ISSUE TITLE
Configurable .aspect dir location?

### ISSUE THREAD

**Issue by aw185176** [aspect-build/rules_js#824]
Is it possible to configure the path of the `.aspect` directory? We would like to avoid adding additional dot folders to the root of our repository.

**Comment by gregmagolan** [comment]
Sure. I will add an attribute to npm_translate_lock to make the output location configurable.

**Comment by gregmagolan** [comment]
Fixed. It will be included in the 1.18.0 release but I'd like to get a few more thing in before cutting that one so in the meantime you can pick it up via the https://github.com/aspect-build/rules_js/commit/af788bce5678d05b8e30f7e5ad126a66960132dd commit

**Comment by ss185994** [comment]
Nice! Thank you!
