### ISSUE TITLE
Support ngcc running on 3p packages that don't ship Angular ivy instructions

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#84]

**Comment by jackvincentnz** [comment]
There is a workaround for this here: https://github.com/aspect-build/bazel-examples/pull/191

**Comment by alexeagle** [comment]
I think Angular now recommends that libraries ship the angular compiler codegen, so ngcc "compatibility compiler" is close enough to End of Life that we'll never fix this.
Closing as obsolete.
