### ISSUE TITLE
[FR]: a rule to produce self-contained NodeJS binaries like --build_python_zip

### ISSUE THREAD

**Issue by tetsuok** [aspect-build/rules_js#877]
### What is the current behavior?

Currently, it seems `js_binary` need to be run with Bazel's output tree as documented [here](https://github.com/aspect-build/rules_js/tree/dbb5af0d2a9a2bb50e4cf4a96dbc582b27567155#running-nodejs-programs). Cannot be run the binary outside of the tree.

`js_image_layer` provides a way to build container images to make `js_binary` self-contained, but container runtime such as Docker needs to run the built image.

### Describe the feature

It would be nice for rules_js to be able to produce a self-contained binary like we can create self-contained Python executables like `py_binary` with `--build_python_zip` or `par_binary`. This enables engineers working in a monorepo to distribute binaries built by Bazel to other engineers so that the other engineers can use tools without re-building those binaries from source.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
Is there prior art that you know of for the shape of a self-contained node binary?

The way we've approached this in the past is the bundle down into a single `.js` file. If you wanted to make the result available to other developers without have to run bazel then you could use `write_source_files` to check the bundle into source control and other developers can run it with `node path/to/checked/in/file.js`

**Comment by gregmagolan** [comment]
You can see an example of this pattern [here](https://github.com/aspect-build/rules_js/blob/67c982afd42de970d6356c4ba2989987a10c5086/js/private/worker/BUILD.bazel#L7) where we check-in the worker bundle into rules_js so that it doesn't need to build from source downstream.

**Comment by alexeagle** [comment]
https://github.com/vercel/ncc is a tool I'm aware of to make a self-contained binary, you could run that under rules_js.

**Comment by tetsuok** [comment]
> (I'm currently seeking how to do this in rules_js, esp, how to teach Bazel the path to node_modules/prettier/bin-prettier.js using the ncc rule generated by @npm//:@vercel/ncc/package_json.bzl is tricky to me)

I just figured it out.

I'm totally fine to close this issue.

**Comment by gregmagolan** [comment]
Great! Would you mind posting your recipe as a comment here for the next person that stumbles upon this pattern?

**Comment by alexeagle** [comment]
For prettier, maybe you just want the one we already publish in here https://github.com/aspect-build/bazel-super-formatter#using-a-formatter-from-a-build-rule ?

**Comment by tetsuok** [comment]
@gregmagolan No problem. I can post the snippet, but maybe sending a PR to https://github.com/aspect-build/bazel-examples is better?

**Comment by tetsuok** [comment]
@alexeagle That's good to know. There is the other case for the prettier binary: build a container image which runs the binary at CI in which just runs the binary without Bazel.

**Comment by gregmagolan** [comment]
Either or @tetsuok. If you have time for a bazel-examples PR that would be great otherwise pasting a snippet here works. 🙏

**Comment by tetsuok** [comment]
I'm pasting a snippet (mostly self-contained).  Copying the following files into a directory, and then running `bazel build //prettier_bin` would produce a self-contained prettier binary built by `ncc` at `bazel-bin/prettier/index.js`.

`package.json`:
```json
{
  "name": "ncc-bin-sample",
  "version": "0.0.1",
  "private": true,
  "devDependencies": {
    "@vercel/ncc": "0.36.1",
    "prettier": "2.8.4"
  }
}
```

`pnpm-lock.yaml`:
```yaml
lockfileVersion: 5.4

specifiers:
  '@vercel/ncc': 0.36.1
  prettier: 2.8.4

devDependencies:
  '@vercel/ncc': 0.36.1
  prettier: 2.8.4

packages:

  /@vercel/ncc/0.36.1:
    resolution: {integrity: sha512-S4cL7Taa9yb5qbv+6wLgiKVZ03Qfkc4jGRuiUQMQ8HGBD5pcNRnHeYM33zBvJE4/zJGjJJ8GScB+WmTsn9mORw==}
    hasBin: true
    dev: true

  /prettier/2.8.4:
    resolution: {integrity: sha512-vIS4Rlc2FNh0BySk3Wkd6xmwxB0FpOndW5fisM5H8hsZSxU2VWVB5CWIkIjWvrHjIhxk2g3bfMKM87zNTrZddw==}
    engines: {node: '>=10.13.0'}
    hasBin: true
    dev: true
```

`WORKSPACE`:
```starlark
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "aspect_rules_js",
    sha256 = "a592fafd8a27b2828318cebbda0003686c6da3318df366b563e8beeffa05a02c",
    strip_prefix = "rules_js-1.21.0",
    url = "https://github.com/aspect-build/rules_js/releases/download/v1.21.0/rules_js-v1.21.0.tar.gz",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@rules_nodejs//nodejs:repositories.bzl", "DEFAULT_NODE_VERSION", "nodejs_register_toolchains")

nodejs_register_toolchains(
    name = "nodejs",
    node_version = DEFAULT_NODE_VERSION,
)

load("@aspect_rules_js//npm:npm_import.bzl", "npm_translate_lock")

npm_translate_lock(
    name = "npm",
    npmrc = "//:.npmrc",
    pnpm_lock = "//:pnpm-lock.yaml",
)

load("@npm//:repositories.bzl", "npm_repositories")

npm_repositories()
```

`BUILD.bazel`:
```starlark
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//:@vercel/ncc/package_json.bzl", ncc_bin = "bin")

npm_link_all_packages()

ncc_bin.ncc(
    name = "prettier_bin",
    srcs = [
        "//:node_modules/prettier",
    ],
    outs = ["prettier"],
    args = [
        "build",
        "node_modules/prettier/bin-prettier.js",
        "--no-cache",
        "-o",
        "prettier",
    ],
    chdir = package_name(),
)
```

**Comment by alexeagle** [comment]
Great - I think since `ncc` already does the thing you ask for and works as a standard npm binary, there's no need for us to add a custom rule for this purpose. Thanks for documenting your solution. If you feel like adding it to aspect-build/bazel-examples that would be a nice spot for it.

**Comment by tgeng** [comment]
Hi, I need to create a self-contained executable for a command line tool written in typescript. I came across this post and followed the setup. But it looks like `ncc` creates an `index.js` in my case rather than an executable. Following is what I have in my BUILD file
```
ts_project(
    name = "pyright_daemon_worker_ts",
    srcs = ["pyright_daemon_worker.ts"],
    allow_js = True,
    source_map = True,
    tsconfig = "tsconfig",
    deps = [
        "node_modules/@types/node",
        "node_modules/@types/express",
        "node_modules/@zzzen/pyright-internal",
        "node_modules/source-map-support",
        "node_modules/express",
        "node_modules/jsonc-parser",
        "node_modules/commander",
        "node_modules/axios",
        "node_modules/body-parser",
    ],
    transpiler = "tsc",
)

ncc_bin.ncc(
    name = "pyright_daemon_worker_ncc",
    srcs = ["pyright_daemon_worker_ts"],
    outs = ["pyright_daemon_worker_bin"],
    args = [
        "build",
        "pyright_daemon_worker.js",
        "--no-cache",
        "-o",
        "pyright_daemon_worker_ncc_out",
    ],
    chdir = package_name(),
    tags = ["requires-network"],
)
```
With this `bazel build :pyright_daemon_worker_ncc` fails because it complains the output is a directory rather than a file. If I cd into the sandbox I can see a `pyright_daemon_worker_ncc_out/index.js` there and `index.js` appears to be a bundled js with (at least some of) the dependencies. @tetsuok how did you get this to work?

**Comment by tgeng** [comment]
ah nvm, I guess I just misunderstood what ncc is designed for. I used https://github.com/vercel/pkg to convert the bundled index.js to a self-contained executable with the following
```
pkg_bin.pkg(
    name = "pyright_daemon_worker_pkg",
    srcs = ["pyright_daemon_worker_ncc"],
    outs = ["pyright_daemon_worker_bin"],
    args = [
        "pyright_daemon_worker_ncc_out/index.js",
        "--no-bytecodes",
        "--public",
        "--output",
        "pyright_daemon_worker_bin",
        "--targets",
        "node22-linux-x64",
    ],
    env = {
        "PKG_CACHE_PATH": ".",
    },
    chdir = package_name(),
    tags = ["requires-network"],
)

```
