### ISSUE TITLE
[Bug]: Multiple `js_image_layer` targets in the same package create clashing artifacts

### ISSUE THREAD

**Issue by iamricard** [aspect-build/rules_js#898]
### What happened?

We have a directory with two js_binary targets. For each, we want to create a different image, so we create two js_image_layer targets. However, js_image_layer uses the bazel package to create the [launcher](https://github.com/aspect-build/rules_js/blob/main/js/private/js_image_layer.bzl#L125) so bazel complains the launcher file is generate by two conflicting actions:

```
ERROR: file 'path/to/project/bazel_package_name_launcher.sh' is generated by these conflicting actions:
Label: //path/to/project/bazel_package_name:from_js_binary_A.layers, //path/to/project/bazel_package_name:from_js_binary_B.layers
RuleClass: js_image_layer rule
...
```

### Version

Development (host) and target OS/architectures: macos arm64

Output of `bazel --version`: 5.2.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: 1.20.0

Language(s) and/or frameworks involved: JS

### How to reproduce

Add a second binary and js_image_layer combo in the rules_docker example https://github.com/aspect-build/rules_js/tree/main/e2e/js_image_docker

### Any other information?

For the time being we're working around this with the following patch:

```diff
# see https://github.com/aspect-build/rules_js/issues/898
diff --git a/js/private/js_image_layer.bzl b/js/private/js_image_layer.bzl
index 6db37e0..917725d 100644
--- a/js/private/js_image_layer.bzl
+++ b/js/private/js_image_layer.bzl
@@ -122,7 +122,7 @@ source {executable_path}

 def _write_laucher(ctx, executable_path):
     "Creates a call-through shell entrypoint which sets BAZEL_BINDIR to '.' then immediately invokes the original entrypoint."
-    launcher = ctx.actions.declare_file("%s_launcher.sh" % ctx.label.package)
+    launcher = ctx.actions.declare_file("%s_%s_launcher.sh" % (ctx.label.package, ctx.attr.name))
     ctx.actions.write(
         output = launcher,
         content = _LAUNCHER_TMPL.format(executable_path = executable_path),
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
cc @thesayyn. How does that patch look to you?

**Comment by alexeagle** [comment]
I think the intent was to use just label.name - the label.package should be redundant.
