### ISSUE TITLE
[Bug]: js_image_layer doesn't work with `--nobuild_runfile_links`

### ISSUE THREAD

**Issue by kormide** [aspect-build/rules_js#902]
### What happened?

The binary's runfiles aren't included in the app layer tar when the `--nobuild_runfile_links` option is set.
### Version

Development (host) and target OS/architectures: osx, arm64

Output of `bazel --version`: 6.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: v1.20.0

### How to reproduce

```shell
cd e2e/js_image_docker
bazel test //... --nobuild_runfile_links
```

**Comment by kormide** [comment]
fyi @thesayyn

**Comment by gregmagolan** [comment]
This intersects with what we do with Workflows so we should figure out what the principled fix is here.

cc @mattem @alexeagle

**Comment by alexeagle** [comment]
I see that the e2e/js_image_oci also fails with that flag.
