### ISSUE TITLE
[FR]: Read pnpm.patches from lockfile when update_pnpm_lock = False

### ISSUE THREAD

**Issue by Toxaris** [aspect-build/rules_js#910]
### What is the current behavior?

When `update_pnpm_lock = True`, `npm_translate_lock` reads the direct dependencies as well as the pnpm patches from the `package.json` files in the repository.

When `update_pnpm_lock = False`, `npm_translate_lock` reads the direct dependencies from the lockfile, and prior to #832, there was no need to even have `package.json` files in the repository. But since #832, the pnpm patches are taken from the `package.json` file in the same folder as the lockfile and the build fails if there is no such `package.json` file.

### Describe the feature

When `update_pnpm_lock = False`, `npm_translate_lock` should not read any `package.json` files in the repository for the following reasons:

1. changes to the `package.json` files should only influence the build after an explicit call to `pnpm install` to regenerate the lockfile. it is inconsistent to apply the pnpm patches but ignore the direct dependencies in the same file.
2. the build should not fail if `package.json` files are missing (and the lockfile was created in some other way).

To achieve this, `npm_translate_lock` should read the pnpm patches from the lockfile if `update_pnpm_lock = False`.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by Toxaris** [comment]
As [discussed on Slack](https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1677445364979689), this is not blocking me, I just created an empty package.json to make the build succeed. I do believe this would be more consistent though, so I wanted to create this feature request to conclude the Slack discussion.

**Comment by gregmagolan** [comment]
As part of this, the docs for `data` and `update_pnpm_lock` should be updated
