### ISSUE TITLE
[Bug]: js_image_layer.mjs: Error: couldn't map o to a path.

### ISSUE THREAD

**Issue by gawi** [aspect-build/rules_js#920]
### What happened?

During invocation of js_image_layer, I get this eror message:
```
file:///home/jpgariep/.cache/bazel/_bazel_jpgariep/dc2fb24bedc6b4555f41da611ff4d0e4/sandbox/linux-sandbox/1030/execroot/nu_workforce/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/aspect_rules_js/js/private/js_image_layer_builder.sh.runfiles/aspect_rules_js/js/private/js_image_layer.mjs:9578
    throw new Error(`couldn't map ${value} to a path. please file a bug at https://github.com/aspect-build/rules_js/issues/new/choose`);

Error: couldn't map o to a path. please file a bug at https://github.com/aspect-build/rules_js/issues/new/choose
    at findKeyByValue (file:///home/jpgariep/.cache/bazel/_bazel_jpgariep/dc2fb24bedc6b4555f41da611ff4d0e4/sandbox/linux-sandbox/1030/execroot/nu_workforce/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/aspect_rules_js/js/private/js_image_layer_builder.sh.runfiles/aspect_rules_js/js/private/js_image_layer.mjs:9578:11)
    at build (file:///home/jpgariep/.cache/bazel/_bazel_jpgariep/dc2fb24bedc6b4555f41da611ff4d0e4/sandbox/linux-sandbox/1030/execroot/nu_workforce/bazel-out/k8-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/aspect_rules_js/js/private/js_image_layer_builder.sh.runfiles/aspect_rules_js/js/private/js_image_layer.mjs:9719:30)
Target //mytarget:image failed to build
```
I've added some trace in the build function around [line 9712](https://github.com/aspect-build/rules_js/blob/f284cb6f0434a3114fce30c70429a15646c409b6/js/private/js_image_layer.mjs#L9712) :
```
root: bazel-out/k8-fastbuild-ST-4a519fd6d3e4/bin
dest: bazel-out/k8-fastbuild-ST-4a519fd6d3e4/bin/external/com_google_protobuf/_virtual_imports/any_proto/google/protobuf/any.proto
realp: /home/jpgariep/.cache/bazel/_bazel_jpgariep/dc2fb24bedc6b4555f41da611ff4d0e4/external/com_google_protobuf/src/google/protobuf/any.proto
output_path: o
```
It seems that the code is assuming that `root` will be somewhere in `realp` but it's not the case here.

I'm building images according to the [documentation here - w/ legacy rules_docker](https://docs.aspect.build/rules/aspect_rules_js/docs/js_image_layer/)

### Version

Development (host) and target OS/architectures:
linux/x86_64

Output of `bazel --version`:
bazel 6.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

v1.20.1

Language(s) and/or frameworks involved:

TypeScript

### How to reproduce

https://github.com/gawi/rules_js/tree/main/e2e/js_image_docker

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by thesayyn** [comment]
Looks like js_image_layer is mishandling an external target. How does the BUILD file look? it's hard to understand what could be wrong here just by looking at the error message.

**Comment by gawi** [comment]
I've tried to make a minimal example. See https://github.com/gawi/rules_js/tree/main/e2e/js_image_docker

**Comment by thesayyn** [comment]
Awesome. this will help
