### ISSUE TITLE
[Bug]: Support for pnpm npm_translate_lock lock_version 6.0

### ISSUE THREAD

**Issue by flolu** [aspect-build/rules_js#971]
### What happened?

After running `pnpm i`, my `pnpm-lock.yaml` updated to `lockfileVersion: '6.0'`, which isn't supported by `rules_js` yet:

```
ERROR: Error computing the main repository mapping: no such package '@npm//': npm_translate_lock currently supports a maximum lock_version of 5.4, but found 6.0. Please file an issue on rules_js
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: bazel 6.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: WORKSPACE

**Comment by flolu** [comment]
Also the syntax seems to have changed in the `pnpm-lock.yaml`:
from
```
lockfileVersion: 5.4
```
to
```
lockfileVersion: '6.0'
```

**Comment by gregmagolan** [comment]
Looks like there are load bearing breaking changes to the lock file that rules_js will have to account for. Should have a PR up later today or tomorrow to support the both v5 and v6 of the pnpm lock file format.

**Comment by gregmagolan** [comment]
#973 should do the trick. Planning to add some tests there before landing.

**Comment by gregmagolan** [comment]
Support for v6 lockfile landed in https://github.com/aspect-build/rules_js/commit/002397780d51735f1a98b362fca7018df31e85ac

I'm going to do some testing downstream over the next week before cutting a release.

**Comment by flolu** [comment]
@gregmagolan thank you so much!
