### ISSUE TITLE
[Bug]: how do we pass NODE_OPTIONS to generated npm package targets 

### ISSUE THREAD

**Issue by taozhou-glean** [aspect-build/rules_js#982]
### What happened?

our target is getting `JavaScript heap out of memory` issue in our remote CI container, but not sure how do we pass NODE_OPTIONS to the generated bin targets here ?

```
load("@npmaspect//:bundlesize2/package_json.bzl", bundlesize_bin = "bin")

bundlesize_bin.bundlesize_test(
    name = "bundlesize_tests",
    args = [
        "--config typescript/bundlesize.config.json",
    ],
    data = [
        "bundlesize.config.json",
        ":webpack",
    ],
)
```

the `js_binary` supports the `node_options` but not sure if here as well.

also it seems that we can increase with `.bazelrc`, but that would be for all targets, wondering if we can just increase for a particular target instead ?

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: 6.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

```
http_archive(
    name = "aspect_rules_js",
    sha256 = "7c50475662810ce9635fa45d718220285a8adef32b2febd8631aae62e5816353",
    strip_prefix = "rules_js-1.23.2",
    url = "https://github.com/aspect-build/rules_js/releases/download/v1.23.2/rules_js-v1.23.2.tar.gz",
)
```

node

**Comment by jbedard** [comment]
You can add any standard node cli options using [node_options](https://docs.aspect.build/rules/aspect_rules_js/docs/js_binary/#node_options-1) such as:
```
bundlesize_bin.bundlesize_test(
    name = "bundlesize_tests",
    ....
    node_options = ["--max-old-space-size=4096"]
)
```

Closing this for now but can continue to discuss here if necessary.
