### ISSUE TITLE
[FR]: Recommendation for 'substitutions' in stamped builds

### ISSUE THREAD

**Issue by gregjacobs** [aspect-build/rules_js#987]
### What is the current behavior?

So I've seen that there is a `stamped_package_json` rule which can help to stamp a `package.json` file with a version number, but we also embed our version number in our `.js` source code itself.

### Describe the feature

I think what I'd ideally like is the functionality that 'substitutions' provided in `rules_nodejs`, which would allow us to replace any text token with a stamped value. And we'd want that on a rule we can use "later in the graph" (as https://github.com/aspect-build/bazel-lib/blob/main/docs/stamping.md describes :)) so as not to rebuild everything when building a stamped version. 

I'm thinking that the build process would be:

1. Compile TypeScript with `ts_project`
2. Create a library with `js_library`
3. Create an npm package solely for pack/publish (**<-- version number stamping would happen in package.json and .js files here**)

Perhaps this would be a good feature to add to `npm_package`? Or, is there any quick way to do a "copy with substitutions" right now that doesn't involve creating a tool for it?

**Comment by gregjacobs** [comment]
Just as an addendum: there's one interesting detail for our team to consider with doing `.js` file replacements for the version number. 

When doing a text replacement for the version in a `.js` file of a published npm library, we don't want to break its source map. So if we do this:

```ts
// Original file content:
const version = "0.0.0-PLACEHOLDER";

// Replaced file content:
const version = "10.1.21";
```

that would throw off the sourcemap's offsets. 

So I'm thinking a solution for this might be something along the lines of the following:

```ts
// Original file content:
const version = "0.0.0-PLACEHOLDER".trim();

// Replaced file content:
const version = "10.1.21          ".trim();
```

Unless there might be a better way?

**Comment by alexeagle** [comment]
https://github.com/aspect-build/bazel-lib/blob/main/docs/expand_template.md is now available for this.
